-- 在 Supabase Auth 创建 demo@example.com 后，将下方 UUID 替换为该用户 id 再执行。
-- 所有记录均明确标记 is_demo=true，不是淘宝真实市场数据。
do $$ begin if exists(select 1 from auth.users where email='demo@example.com') then
 insert into profiles(id,display_name) select id,'Demo 店主' from auth.users where email='demo@example.com' on conflict do nothing;
 insert into suppliers(user_id,name,platform,rating,is_demo) select u.id,x.name,'1688',x.rating,true from auth.users u cross join (values('义乌宠物清洁用品厂',4.7),('临沂猫砂周边供应链',4.5),('宁波宠物玩具制品厂',4.3)) x(name,rating) where u.email='demo@example.com' and not exists(select 1 from suppliers s where s.user_id=u.id and s.name=x.name);
 insert into skus(user_id,sku_code,name,category,cost,sale_price,stock,status,is_demo) select u.id,x.code,x.name,x.category,x.cost,x.price,x.stock,x.status::sku_status,true from auth.users u cross join (values ('S001','双面宠物去毛器','猫咪清洁',11.8,39.9,86,'testing'),('S002','双层猫砂防带出垫','猫咪清洁',16.5,49.9,62,'watching'),('S003','猫砂铲收纳座套装','猫咪清洁',8.6,29.9,104,'potential'),('S004','可替换芯猫抓板','猫咪家居',21.5,59.9,48,'testing'),('S005','可替换头逗猫棒','猫咪玩耍',5.2,19.9,135,'testing')) x(code,name,category,cost,price,stock,status) where u.email='demo@example.com' on conflict(user_id,sku_code) do update set name=excluded.name,category=excluded.category,cost=excluded.cost,sale_price=excluded.sale_price,stock=excluded.stock,status=excluded.status,is_demo=true;
 insert into candidate_products(user_id,name,category,total_score,status,notes,is_demo)
 select u.id,x.name,x.category,x.score,x.status::candidate_status,x.notes,true from auth.users u cross join (values
 ('双面宠物去毛器','清洁线',91,'approved','检查刮面是否损伤织物'),('双层猫砂防带出垫','清洁线',89,'approved','检查材质气味与防滑性'),('猫砂铲收纳座套装','清洁线',87,'approved','检查承重与边缘毛刺'),('可替换芯猫抓板','家居线',84,'sample','确认胶黏剂与粉尘'),('可替换头逗猫棒','玩耍线',82,'sample','检查绳线、小零件和脱落风险'),('透明沙发防抓贴','家居线',80,'researching','测试残胶'),('硅胶食盆防滑垫','家居线',79,'researching','确认材质'),('无铃铛猫玩具球','玩耍线',77,'candidate','检查吞咽风险'),('可折叠猫隧道','玩耍线',74,'candidate','检查钢圈包边'),('猫玩具收纳篮','收纳线',73,'candidate','检查编织毛刺'),('可水洗粘毛滚筒','清洁线',81,'researching','测试粘性衰减'),('猫砂垃圾袋收纳盒','清洁线',76,'candidate','检查抽取顺畅度'),('猫砂盆侧挂收纳盒','收纳线',75,'candidate','确认适配范围'),('家具边角猫抓保护垫','家居线',78,'researching','测试固定方式'),('平板替换式猫抓芯','家居线',83,'sample','检查纸屑与胶黏剂'),('猫毛清洁静电刷','清洁线',80,'candidate','检查刷毛牢固度'),('毛毡猫窝收纳凳','家居线',68,'candidate','检查承重与气味'),('硅胶梳毛按摩刷','清洁线',70,'candidate','检查梳齿柔软度'),('纸袋型猫咪躲藏玩具','玩耍线',72,'candidate','检查油墨与碎片'),('门后逗猫弹力玩具','玩耍线',66,'researching','检查缠绕和连接件')) x(name,category,score,status,notes) where u.email='demo@example.com' and not exists(select 1 from candidate_products c where c.user_id=u.id and c.name=x.name);
 insert into sku_daily_metrics(user_id,sku_id,date,impressions,clicks,visitors,favorites,add_to_cart,orders,units_sold,revenue,refund_orders,refund_amount,ad_spend,is_demo)
 select s.user_id,s.id,d::date,1800+extract(day from d)::int*37+substring(s.sku_code from 2)::int*220,70+extract(day from d)::int*2+substring(s.sku_code from 2)::int*9,62+extract(day from d)::int*2+substring(s.sku_code from 2)::int*8,8,12+substring(s.sku_code from 2)::int,2+substring(s.sku_code from 2)::int,2+substring(s.sku_code from 2)::int,round(((2+substring(s.sku_code from 2)::int)*s.sale_price)::numeric,2),case when extract(day from d)::int%11=0 then 1 else 0 end,case when extract(day from d)::int%11=0 then s.sale_price else 0 end,round((((2+substring(s.sku_code from 2)::int)*s.sale_price)*0.12)::numeric,2),true
 from skus s cross join generate_series(date '2026-07-20',date '2026-08-18',interval '1 day') d where s.user_id=(select id from auth.users where email='demo@example.com' limit 1)
 on conflict(sku_id,date) do update set impressions=excluded.impressions,clicks=excluded.clicks,visitors=excluded.visitors,favorites=excluded.favorites,add_to_cart=excluded.add_to_cart,orders=excluded.orders,units_sold=excluded.units_sold,revenue=excluded.revenue,refund_orders=excluded.refund_orders,refund_amount=excluded.refund_amount,ad_spend=excluded.ad_spend,is_demo=true;
end if; end $$;
