import Link from "next/link";

const lifecycle=["已发现","找货中","候选","待上架","测试销售","增长","稳定","衰退","清仓","停止经营"];
const modules=["经营总览","AI 店长","SKU 生命周期","经营策略","采购策略","AI 权限"];
export default function ReviewPage(){return <div className="review-shell"><aside className="review-side"><div><div className="brand">AI 猫咪居家生活用品店</div><span className="review-badge">公开只读审阅</span></div><nav>{modules.map(item=><a href={`#${item}`} key={item}>{item}</a>)}</nav><Link href="/login" className="button-link secondary-btn">进入正式后台</Link></aside><main className="review-main"><header className="review-hero"><div><div className="eyebrow">Public Product Review</div><h1>AI 店长核心经营框架</h1><p>该页面仅用于产品审阅，不读取真实店铺数据，不开放写入、AI 调用、1688 采集或采购操作。</p></div><span>版本：核心框架 V1</span></header>
  <section id="经营总览"><div className="section-heading"><div><h2>经营总览</h2><p>AI 持续观察店铺状态，并把事实、判断和行动分开。</p></div></div><div className="metric-grid"><div className="card"><span className="muted">店铺阶段</span><div className="metric">起店期</div></div><div className="card"><span className="muted">核心客群</span><div className="metric">养猫家庭</div></div><div className="card"><span className="muted">目标毛利率</span><div className="metric">45%</div></div><div className="card"><span className="muted">人工待审核</span><div className="metric">关键动作</div></div></div></section>
  <section id="AI 店长" className="card review-section"><div className="eyebrow">Observe → Diagnose → Plan → Execute → Evaluate</div><h2>AI 店长决策中枢</h2><div className="review-decision-grid"><div><h3>今日状态</h3><ul><li>读取 SKU、销售、任务和供应商状态</li><li>确定当前最重要的经营问题</li><li>区分确定性规则与 AI 判断</li></ul></div><div><h3>行动建议</h3><ul><li>是否引进某个商品</li><li>选择哪个供应商</li><li>补货、优化、调价或淘汰</li></ul></div><div><h3>人工边界</h3><ul><li>上架、改价和投放必须审核</li><li>联系供应商必须审核</li><li>1688 实际采购由店主完成</li></ul></div></div></section>
  <section id="SKU 生命周期" className="card review-section"><div className="eyebrow">Product Lifecycle</div><h2>SKU 全生命周期</h2><div className="review-lifecycle">{lifecycle.map((item,index)=><div key={item}><b>{String(index+1).padStart(2,"0")}</b><span>{item}</span></div>)}</div><p className="muted">每次变化记录触发数据、AI 判断、建议动作、审批状态和最终执行结果。</p></section>
  <section id="经营策略" className="card review-section"><div className="eyebrow">Store Strategy</div><h2>经营策略</h2><div className="review-policy-grid">{[["店铺阶段","起店期"],["主营类目","猫咪玩具与居家生活用品"],["核心客群","养猫家庭"],["目标 SKU","15～25（软目标）"],["目标库存周期","≤ 30 天"],["价格策略","利润优先"],["风险偏好","30 / 100"],["新品探索强度","50 / 100"]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></section>
  <section id="采购策略" className="card review-section"><div className="eyebrow">Procurement Policy</div><h2>1688 采购策略</h2><div className="review-policy-grid">{[["采购方式","一件代发"],["采购成本范围","¥2～¥30"],["MOQ 上限","5"],["最低回头率","20%"],["异常低价","进入人工核价"],["数据未解析","进入人工复核"],["源头工厂","优先"],["先采后付","优先"]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="notice">搜索质量、AI 复核数量、复杂优惠价格、可持续到手成本和一件代发核验已列为后续优化项。</div></section>
  <section id="AI 权限" className="card review-section"><div className="eyebrow">AI Governance</div><h2>AI 权限</h2><div className="permission-columns"><div><h3>可以自动准备</h3><ul><li>读取与分析数据</li><li>搜索货源、规则评分与聚类</li><li>生成内容和定价草案</li><li>创建任务、实验和报告</li></ul></div><div><h3>必须人工审核</h3><ul><li>淘宝正式上架与改价</li><li>广告预算调整</li><li>联系供应商</li><li>下架、清仓与实际采购</li></ul></div></div></section>
  <footer className="review-footer">公开审阅页不包含真实经营数据。<Link href="/login">登录正式后台</Link></footer>
  </main></div>}
