import type{PurchasePreflight,StoreState,TaobaoOrder}from"../domain";
export function getOrderParts(s:StoreState,o:TaobaoOrder){const taobaoSku=s.taobaoSkus.find(x=>x.id===o.taobaoSkuId),product=s.taobaoProducts.find(x=>x.id===taobaoSku?.productId),mapping=s.skuMappings.find(x=>x.taobaoSkuId===taobaoSku?.id),sourceSku=s.sourceSkus.find(x=>x.id===mapping?.sourceSkuId),supplier=s.suppliers.find(x=>x.id===mapping?.supplierId);return{taobaoSku,product,mapping,sourceSku,supplier}}
export function calculateOrderProfit(s:StoreState,id:string){const o=s.orders.find(x=>x.id===id);if(!o)return null;const{taobaoSku,mapping,sourceSku}=getOrderParts(s,o);if(!taobaoSku)return null;const po=s.purchaseOrders.find(x=>x.orderId===id),purchase=(po?.actualPurchaseCost??sourceSku?.purchasePrice??mapping?.purchasePriceSnapshot??0)*o.quantity,shipping=po?.actualShippingCost??sourceSku?.shippingFee??mapping?.shippingFeeSnapshot??0,revenue=taobaoSku.salePrice*o.quantity,profit=revenue-purchase-shipping-o.platformCost-o.afterSalesCost;return{revenue,purchase,shipping,platform:o.platformCost,afterSales:o.afterSalesCost,profit,margin:revenue?profit/revenue:0}}
export function purchasePreflight(s:StoreState,id:string):PurchasePreflight{const o=s.orders.find(x=>x.id===id);if(!o)return{canPurchase:false,requiresApproval:true,purchaseCost:0,shippingCost:0,expectedProfit:0,expectedMargin:0,checks:[{key:"order",label:"订单",passed:false,detail:"订单不存在"}]};const{taobaoSku,mapping,sourceSku,supplier}=getOrderParts(s,o),profit=calculateOrderProfit(s,id);const checks=[{key:"paid",label:"订单已付款",passed:Boolean(o.paidAt),detail:o.paidAt?"淘宝 Mock 订单已付款":"订单未付款"},{key:"mapping",label:"SKU Mapping",passed:Boolean(taobaoSku&&mapping&&mapping.status!=="INVALID"),detail:mapping?`${taobaoSku?.code} → ${sourceSku?.id??"未找到"}`:"未建立货源映射"},{key:"inventory",label:"Inventory",passed:Boolean(sourceSku&&sourceSku.status==="ACTIVE"&&sourceSku.inventory>=o.quantity),detail:sourceSku?`库存 ${sourceSku.inventory}`:"无货源 SKU"},{key:"price",label:"采购价格",passed:Boolean(sourceSku&&mapping&&sourceSku.purchasePrice===mapping.purchasePriceSnapshot),detail:sourceSku&&mapping?`当前 ¥${sourceSku.purchasePrice.toFixed(2)} / 快照 ¥${mapping.purchasePriceSnapshot.toFixed(2)}`:"无法核对"},{key:"supplier",label:"Supplier",passed:Boolean(supplier&&supplier.status==="APPROVED"&&supplier.sampleVerified),detail:supplier?`${supplier.name} · ${supplier.status}`:"供应商不存在"},{key:"dropship",label:"Dropshipping",passed:Boolean(supplier?.supportsDropshipping&&supplier.supportsTaobaoPrivacy&&supplier.supportsTaobaoWaybill),detail:supplier?.supportsDropshipping?"支持一件代发、淘宝密文和面单":"代发能力不完整"},{key:"profit",label:"Profit",passed:Boolean(profit&&profit.profit>=s.minProfitAmount&&profit.margin>=s.minProfitMargin),detail:profit?`预计 ¥${profit.profit.toFixed(2)} / ${(profit.margin*100).toFixed(1)}%`:"无法计算"}];return{canPurchase:checks.every(x=>x.passed),requiresApproval:true,purchaseCost:(sourceSku?.purchasePrice??0)*o.quantity,shippingCost:sourceSku?.shippingFee??0,expectedProfit:profit?.profit??0,expectedMargin:profit?.margin??0,checks}}
export function dashboardMetrics(s:StoreState){const completed=s.orders.filter(x=>x.fulfillmentStatus==="COMPLETED");return{pending:s.orders.filter(x=>x.fulfillmentStatus==="PURCHASE_REQUIRED").length,approvals:s.aiActions.filter(x=>x.status==="APPROVAL_REQUIRED").length,exceptions:s.orders.filter(x=>x.fulfillmentStatus==="EXCEPTION").length,completed:completed.length,profit:completed.reduce((n,x)=>n+(x.actualProfit??calculateOrderProfit(s,x.id)?.profit??0),0),revenue:s.orders.reduce((n,x)=>n+(getOrderParts(s,x).taobaoSku?.salePrice??0)*x.quantity,0),orders:s.orders.length,processing:s.orders.filter(x=>x.fulfillmentStatus==="SUPPLIER_PROCESSING").length,inTransit:s.orders.filter(x=>["SUPPLIER_SHIPPED","TAOBAO_SHIPPED","IN_TRANSIT"].includes(x.fulfillmentStatus)).length}}

export function selectDashboard(s:StoreState){
  const metrics=dashboardMetrics(s);
  const approvalCards=s.aiActions.filter(x=>x.status==="APPROVAL_REQUIRED").map(a=>{const o=s.orders.find(x=>x.id===a.orderId),p=o?getOrderParts(s,o):null,profit=o?calculateOrderProfit(s,o.id):null;return{id:`action-${a.id}`,priority:a.riskLevel==="HIGH"?"高风险":"重要",entity:o?`淘宝订单 #${o.orderNo}`:"AI Action",title:a.title,diagnosis:a.summary,recommendation:a.type==="PURCHASE"?"人工复核后批准 Mock 1688 采购。":"检查风险原因后决定是否继续履约。",impact:a.type==="PURCHASE"?"批准后订单将进入供应商处理阶段。":"避免异常订单继续扩大损失。",facts:[{label:"商品",value:p?.product?.title??"-"},{label:"预计利润",value:profit?`¥${profit.profit.toFixed(2)}`:"-"},{label:"当前状态",value:o?.fulfillmentStatus??a.status}],href:o?`/fulfillment/orders/${o.id}`:"/ai-manager"}});
  const pendingCards=s.orders.filter(x=>x.fulfillmentStatus==="PURCHASE_REQUIRED").map(o=>{const p=getOrderParts(s,o),profit=calculateOrderProfit(s,o.id);return{id:`order-${o.id}`,priority:"重要",entity:`淘宝订单 #${o.orderNo}`,title:"已付款，等待 Purchase Preflight",diagnosis:"订单尚未进行采购前检查，系统不会直接向 1688 下单。",recommendation:"核对 SKU 映射、库存、供应商和利润后生成采购建议。",impact:"通过人工审批后进入供应商处理。",facts:[{label:"商品",value:p.product?.title??"-"},{label:"订单金额",value:`¥${((p.taobaoSku?.salePrice??0)*o.quantity).toFixed(2)}`},{label:"预计利润",value:`¥${(profit?.profit??0).toFixed(2)}`}],href:`/fulfillment/orders/${o.id}`}});
  const exceptionCards=s.orders.filter(x=>x.fulfillmentStatus==="EXCEPTION").map(o=>{const p=getOrderParts(s,o);return{id:`exception-${o.id}`,priority:"高风险",entity:`淘宝订单 #${o.orderNo}`,title:o.exception??"履约异常",diagnosis:"当前履约状态已触发异常规则，需要人工检查供应商或物流。",recommendation:"进入订单详情核对异常原因并联系供应商。",impact:"及时处理可降低退款和差评风险。",facts:[{label:"商品",value:p.product?.title??"-"},{label:"供应商",value:p.supplier?.name??"-"},{label:"状态",value:"履约异常"}],href:`/fulfillment/orders/${o.id}`}});
  const opportunities=s.skuMappings.filter(x=>x.status==="ACTIVE").map(m=>{const tb=s.taobaoSkus.find(x=>x.id===m.taobaoSkuId),product=s.taobaoProducts.find(x=>x.id===tb?.productId),supplier=s.suppliers.find(x=>x.id===m.supplierId);return{id:m.id,name:product?.title??tb?.code??"商品",score:Math.round(Math.min(99,60+m.expectedMargin*80+(supplier?.sampleVerified?5:0))),detail:`预计利润 ¥${m.expectedProfit.toFixed(2)} · 利润率 ${(m.expectedMargin*100).toFixed(1)}%`,href:"/skus"}}).sort((a,b)=>b.score-a.score);
  const opportunityCards=opportunities.slice(0,1).map(x=>{return{id:`opportunity-${x.id}`,priority:"机会",entity:"商品机会",title:`${x.name} 值得继续经营`,diagnosis:"SKU 映射有效，供应商通过验证，当前利润空间高于经营阈值。",recommendation:"保持销售并持续观察采购价格与库存。",impact:"稳定贡献高质量订单和利润。",facts:[{label:"AI 评分",value:`${x.score} / 100`},{label:"经营空间",value:x.detail.split(" · ")[0]},{label:"状态",value:"映射正常"}],href:x.href}});
  const priorities=[...exceptionCards,...approvalCards,...pendingCards,...opportunityCards].slice(0,3);
  const fulfillment=[{label:"待采购",count:metrics.pending,detail:metrics.pending?"等待采购前检查":"当前无待采购订单"},{label:"供应商处理中",count:metrics.processing,detail:metrics.processing?"等待供应商发货":"暂无处理中订单"},{label:"运输中",count:metrics.inTransit,detail:metrics.inTransit?"物流状态持续同步":"暂无在途订单"},{label:"今日完成",count:metrics.completed,detail:metrics.completed?`实际利润 ¥${metrics.profit.toFixed(2)}`:"等待订单完成"}];
  const exceptions:Array<{id:string;title:string;detail:string;href:string;level:"高"|"中"}>=s.orders.filter(x=>x.fulfillmentStatus==="EXCEPTION").map(o=>{const p=getOrderParts(s,o);return{id:o.id,title:o.exception??"履约异常",detail:`${o.orderNo} · ${p.product?.title??"未知商品"}`,href:`/fulfillment/orders/${o.id}`,level:"高"}});s.skuMappings.filter(x=>x.status!=="ACTIVE").forEach(m=>{const tb=s.taobaoSkus.find(x=>x.id===m.taobaoSkuId),src=s.sourceSkus.find(x=>x.id===m.sourceSkuId);exceptions.push({id:m.id,title:m.status==="OUT_OF_STOCK"?"1688 SKU 缺货":"SKU 映射需要复核",detail:`${tb?.code??"未知 SKU"} · 库存 ${src?.inventory??0}`,href:"/skus",level:m.status==="OUT_OF_STOCK"?"高":"中"})});
  const recentActions=[...s.aiActions].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,5).map(a=>({id:a.id,time:new Date(a.createdAt).toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit"}),action:a.title,target:s.orders.find(x=>x.id===a.orderId)?.orderNo??"经营对象",status:a.status,result:a.summary}));
  return{metrics,priorities,fulfillment,opportunities:opportunities.slice(0,3),exceptions:exceptions.slice(0,4),recentActions};
}
