"use client";
import Link from"next/link";import{useState}from"react";import{useStore}from"@/components/store/store-provider";import{selectDashboard}from"@/lib/v2/services/store";
export function UnifiedDashboard(){const{state,ready,reset,runDailyLoop}=useStore(),[running,setRunning]=useState(false),[loopMessage,setLoopMessage]=useState("");if(!ready)return <div className="ai-loading"><span className="spinner"/>正在载入今日经营状态…</div>;const view=selectDashboard(state),m=view.metrics,summary=m.pending?`今天有 ${m.pending} 笔已付款订单等待采购，建议优先完成采购前检查。`:m.approvals?`有 ${m.approvals} 个经营动作等待你批准。`:m.exceptions?`发现 ${m.exceptions} 个履约异常，需要优先检查。`:m.inTransit?`有 ${m.inTransit} 笔订单正在运输，当前履约持续推进。`:"今日经营检查已完成，当前没有新的阻塞项。";function run(){setRunning(true);setLoopMessage("");const count=runDailyLoop();setTimeout(()=>{setRunning(false);setLoopMessage(count?`已完成检查并生成 ${count} 个待审批采购动作。`:"已完成检查，暂未发现新的待审批动作。")},650)}return <div className="ops-dashboard">
<header className="ops-header"><div><div className="ops-store">{state.storeName} <span className="demo-badge">DEMO DATA</span></div><h1>经营总览</h1><p><span className="status-dot"/>AI 店长已完成今日检查 · {m.exceptions?`${m.exceptions} 个异常需要关注`:"经营状态持续更新"}</p></div><div className="dashboard-header-actions"><button className="reset-link" onClick={reset}>重置 Demo</button><button className="btn" disabled={running} onClick={run}>{running?"正在运行决策循环…":"运行今日决策循环"}</button></div></header>
<section className="ai-daily-summary"><div className="ai-mark">AI</div><div><span>AI 今日总结</span><h2>{summary}</h2>{loopMessage&&<p className="loop-message">{loopMessage}</p>}</div><Link href="/ai-manager">查看完整判断 →</Link></section>
<section className="ops-kpis">{[{label:"今日销售额",value:`¥${m.revenue.toFixed(2)}`,detail:`来自 ${m.orders} 笔淘宝订单`,tone:"success"},{label:"今日订单",value:m.orders,detail:`${m.completed} 笔已完成`},{label:"实际利润",value:`¥${m.profit.toFixed(2)}`,detail:m.completed?`${m.completed} 笔订单已核算`:"订单完成后自动核算",tone:"success"},{label:"待采购",value:m.pending,detail:m.pending?"等待 Purchase Preflight":"暂无待采购",tone:m.pending?"warning":""},{label:"待审批",value:m.approvals,detail:m.approvals?"关键动作需人工确认":"暂无待审批",tone:m.approvals?"warning":""},{label:"物流异常",value:m.exceptions,detail:m.exceptions?"建议今天处理":"履约状态正常",tone:m.exceptions?"danger":""}].map(x=><article className={`ops-kpi ${x.tone}`} key={x.label}><span>{x.label}</span><strong>{x.value}</strong><small>{x.detail}</small></article>)}</section>
<SectionTitle over="需要处理" title="按优先级处理今日经营动作"><Link href="/tasks">查看全部待办 →</Link></SectionTitle><section className="priority-board">{view.priorities.map(a=><article className={`priority-action ${a.priority==="高风险"?"critical":""}`} key={a.id}><div className="priority-top"><span className={`priority-chip ${a.priority}`}>{a.priority}</span><span>{a.entity}</span></div><h3>{a.title}</h3><div className="action-facts">{a.facts.map(f=><div key={f.label}><span>{f.label}</span><b>{f.value}</b></div>)}</div><div className="ai-reason"><b>AI 判断</b><p>{a.diagnosis}</p><b>建议</b><p>{a.recommendation}</p></div><p className="impact"><b>预计影响：</b>{a.impact}</p><div className="action-buttons"><Link className="btn button-link" href={a.href}>处理事项</Link></div></article>)}{!view.priorities.length&&<div className="empty-state">今日经营动作均已处理完成。</div>}</section>
<div className="ops-two-column"><section><SectionTitle over="订单履约" title="从淘宝付款到订单完成"><Link href="/fulfillment/orders">查看订单 →</Link></SectionTitle><div className="fulfillment-grid">{view.fulfillment.map(x=><Link href="/fulfillment/orders" className={`fulfillment-step ${x.count?"active":""}`} key={x.label}><span>{x.label}</span><strong>{x.count}</strong><small>{x.detail}</small></Link>)}</div></section><section><SectionTitle over="商品机会" title="值得继续经营的商品"><Link href="/skus">查看 SKU →</Link></SectionTitle><div className="stack-list">{view.opportunities.map(x=><Link href={x.href} key={x.id}><b>{x.name}</b><span>{x.detail}</span><em>{x.score}</em></Link>)}</div></section></div>
<div className="ops-two-column lower"><section><SectionTitle over="经营异常" title="已发现并等待处理"><Link href="/fulfillment/orders">查看履约 →</Link></SectionTitle><div className="exception-list">{view.exceptions.map(x=><Link href={x.href} key={x.id}><span className={`exception-level l${x.level}`}>{x.level}</span><div><b>{x.title}</b><small>{x.detail}</small></div><span>→</span></Link>)}{!view.exceptions.length&&<div className="empty-state">当前没有经营异常</div>}</div></section><section><SectionTitle over="AI 最近动作" title="经营动作全程留痕"><Link href="/ai-manager">查看 AI 店长 →</Link></SectionTitle><div className="action-log">{view.recentActions.map(x=><div key={x.id}><time>{x.time}</time><span><b>{x.action}</b><small>{x.target} · {x.result}</small></span><em>{x.status}</em></div>)}{!view.recentActions.length&&<div className="empty-state">运行今日决策循环后，AI 动作会显示在这里。</div>}</div></section></div></div>}
function SectionTitle({over,title,children}:{over:string;title:string;children?:React.ReactNode}){return <div className="ops-section-title"><div><span>{over}</span><h2>{title}</h2></div>{children}</div>}
