"use client";

import { useEffect, useMemo, useRef, useState } from "react";

type Breakdown = { profit:number; demand:number; supplier:number; afterSales:number; storeFit:number; competition:number; differentiation:number };
interface Item { id:string; title:string; source_url:string; price_min:number|null; minimum_order_quantity:number|null; sales_count:number|null; repurchase_rate:number|null; return_shipping:boolean; pay_later:boolean; dropshipping:boolean; cluster_key:string|null; cluster_rank:number|null; data_status:"valid"|"needs_review"|"data_error"|"rejected"; data_issues:string[]; rejected_reasons:string[]; rough_score:number; score_breakdown:Breakdown; estimated_sale_price_min:number|null; estimated_sale_price_max:number|null; estimated_unit_profit_min:number|null; estimated_unit_profit_max:number|null; decision_status:"pending"|"candidate"|"ignored" }
interface Pick { id:string; score:number; ruleScore:number; qualitativeScore:number; reason:string; risks:string[]; checks:string[]; scoreBreakdown:Breakdown }
interface Stats { fetched:number; unique:number; pages:number; relevant:number; dataErrors:number; rejected:number; clusters:number; eligible:number }

export function SourcingDiscovery() {
  const [query,setQuery]=useState("猫咪去毛清洁用品");
  const [keywordText,setKeywordText]=useState("宠物去毛器\n猫毛清理器\n沙发除猫毛\n宠物除毛刷");
  const [items,setItems]=useState<Item[]>([]);
  const [runId,setRunId]=useState("");
  const [picks,setPicks]=useState<Pick[]>([]);
  const [stats,setStats]=useState<Stats|null>(null);
  const [collecting,setCollecting]=useState(false);
  const [reviewing,setReviewing]=useState(false);
  const captureTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
  const captureRequestId=useRef<string|null>(null);
  const [error,setError]=useState("");
  async function post(url:string,data:object){const response=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const body=await response.json();if(!response.ok)throw new Error(body.error??"操作失败");return body}
  useEffect(()=>{void fetch("/api/sourcing/latest").then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error??"读取最近任务失败");if(!body.runId)return;setRunId(body.runId);setItems(body.products??[]);setPicks(body.picks??[]);setStats(body.stats);if(body.query)setQuery(body.query);if(body.keywords?.length)setKeywordText(body.keywords.join("\n"))}).catch(reason=>setError(reason.message))},[]);
  useEffect(()=>{const receive=(event:MessageEvent)=>{if(event.origin!==location.origin||event.data?.type!=="AI_SHOP_CAPTURE_RESULT"||event.data.requestId!==captureRequestId.current)return;if(captureTimer.current)clearTimeout(captureTimer.current);captureTimer.current=null;captureRequestId.current=null;if(event.data.error){setCollecting(false);setError(event.data.error);return}const keywords=keywordText.split(/[\n,，]/).map(value=>value.trim()).filter(Boolean).slice(0,5);void post("/api/sourcing/browser-import",{query,keywords,collection:event.data.collection,items:event.data.items}).then(body=>{setItems(body.products??[]);setRunId(body.runId);setStats(body.stats);setPicks([])}).catch(reason=>setError(reason.message)).finally(()=>setCollecting(false))};window.addEventListener("message",receive);return()=>window.removeEventListener("message",receive)},[query,keywordText]);
  useEffect(()=>()=>{if(captureTimer.current)clearTimeout(captureTimer.current)},[]);
  function capture(){const keywords=keywordText.split(/[\n,，]/).map(value=>value.trim()).filter(Boolean).slice(0,5);if(keywords.length<3){setError("每个品类请填写 3～5 个关键词");return}const requestId=crypto.randomUUID();captureRequestId.current=requestId;setCollecting(true);setError("");window.postMessage({type:"AI_SHOP_CAPTURE_1688",requestId,query,keywords,maxPages:3},location.origin);captureTimer.current=setTimeout(()=>{captureRequestId.current=null;captureTimer.current=null;setCollecting(false);setError("采集超时；最多 5 个关键词 × 3 页，请检查 1688 标签页后重试")},180000)}
  async function review(){setReviewing(true);setError("");try{const body=await post("/api/sourcing/shortlist",{runId,limit:20});setPicks(body.items??[])}catch(reason){setError(reason instanceof Error?reason.message:"细筛失败")}finally{setReviewing(false)}}
  async function decide(id:string,action:"candidate"|"ignored"){try{await post("/api/sourcing/decision",{id,action});setItems(current=>current.map(item=>item.id===id?{...item,decision_status:action}:item))}catch(reason){setError(reason instanceof Error?reason.message:"操作失败")}}
  const byId=useMemo(()=>new Map(items.map(item=>[item.id,item])),[items]);
  return <>
    <section className="card"><h2>品类选品任务</h2><p className="muted">每个关键词最多 3 页；串行低频抓取，跨页去重；新增有效商品率低于 15% 或没有新类型时自动停止。</p><div className="sourcing-task-form"><label>任务名称<input className="input" value={query} onChange={event=>setQuery(event.target.value)}/></label><label>搜索关键词（每行一个，3～5 个）<textarea className="input textarea" value={keywordText} onChange={event=>setKeywordText(event.target.value)}/></label><div className="auth-actions"><button type="button" className="btn" disabled={collecting||reviewing} onClick={capture}>{collecting?"正在低频采集…":"开始品类采集"}</button>{runId&&<button type="button" className="secondary-btn" disabled={collecting||reviewing||!stats?.eligible} onClick={()=>void review()}>{reviewing?"DeepSeek 复核中…":"DeepSeek 复核（最多20个方向）"}</button>}</div></div>{error&&<div className="status-box error">{error}</div>}</section>
    {stats&&<div className="sourcing-stats"><div><b>{stats.pages}</b><span>实际页数</span></div><div><b>{stats.fetched}</b><span>原始 listing</span></div><div><b>{stats.unique}</b><span>跨词去重后</span></div><div><b>{stats.dataErrors+stats.rejected}</b><span>异常/硬淘汰</span></div><div><b>{stats.clusters}</b><span>商品方向</span></div><div><b>{stats.eligible}</b><span>可供 AI 复核</span></div></div>}
    {picks.map((pick,index)=>{const item=byId.get(pick.id);if(!item)return null;const b=item.score_breakdown;return <article className="card sourcing-card" key={pick.id}><div className="sourcing-card-head"><div><span className="eyebrow">#{index+1} · {item.cluster_key}</span><h2>{item.title}</h2></div><div className="sourcing-score"><b>{pick.score}</b><span>综合分</span></div></div><div className="sourcing-economics"><div><span>采购</span><b>{item.price_min==null?"待核实":`¥${item.price_min}`}</b><small>MOQ {item.minimum_order_quantity??"待核实"}</small></div><div><span>预计售价</span><b>¥{item.estimated_sale_price_min}～{item.estimated_sale_price_max}</b><small>含运费/包装/推广/售后预留</small></div><div><span>预计单件利润</span><b>¥{item.estimated_unit_profit_min}～{item.estimated_unit_profit_max}</b><small>目标利润≥¥5、利润率≥40%</small></div></div><div className="sourcing-columns"><div><h3>核心指标</h3><p>销量：{item.sales_count??"待核实"}　回头率：{item.repurchase_rate==null?"待核实":`${item.repurchase_rate}%`}</p><p>退货包运费：{item.return_shipping?"✓":"待核实"}　先采后付：{item.pay_later?"✓":"待核实"}　一件代发：{item.dropshipping?"✓":"待核实"}</p><h3>规则评分</h3><div className="score-grid"><span>利润 {b.profit}/25</span><span>销量 {b.demand}/15</span><span>供应商 {b.supplier}/20</span><span>售后 {b.afterSales}/10</span><span>店铺匹配 {b.storeFit}/15</span><span>竞争 {b.competition}/10</span><span>差异化 {b.differentiation}/5</span></div></div><div><h3>AI 判断</h3><p>{pick.reason}</p><p><b>风险：</b>{pick.risks.join("；")}</p><p><b>人工复核：</b>{pick.checks.join("；")}</p></div></div><div className="sourcing-actions"><a className="text-link" href={item.source_url} target="_blank" rel="noreferrer">查看 1688 详情</a><button className="secondary-btn" disabled={item.decision_status==="ignored"} onClick={()=>void decide(item.id,"ignored")}>{item.decision_status==="ignored"?"已忽略":"忽略"}</button><button className="btn" disabled={item.decision_status==="candidate"} onClick={()=>void decide(item.id,"candidate")}>{item.decision_status==="candidate"?"已加入选品池":"加入选品池"}</button></div></article>})}
    {items.length>0&&<div className="card table-wrap"><h2>清洗与硬过滤明细</h2><table className="table"><thead><tr><th>商品/聚类</th><th>数据状态</th><th>采购价</th><th>销量/回头率</th><th>规则分</th><th>问题</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td><a href={item.source_url} target="_blank" rel="noreferrer">{item.title}</a><br/><small>{item.cluster_key} · 类内#{item.cluster_rank}</small></td><td><span className={`data-state ${item.data_status}`}>{item.data_status.toUpperCase()}</span></td><td>{item.price_min==null?"—":`¥${item.price_min}`}<br/><small>MOQ {item.minimum_order_quantity??"—"}</small></td><td>{item.sales_count??"—"}<br/><small>{item.repurchase_rate==null?"—":`${item.repurchase_rate}%`}</small></td><td>{item.data_status==="valid"?item.rough_score:"—"}</td><td>{[...(item.data_issues||[]),...(item.rejected_reasons||[])].join("；")||"—"}</td></tr>)}</tbody></table></div>}
  </>;
}
