export type PriceStatus="VERIFIED"|"HIGH_CONFIDENCE"|"NEEDS_REVIEW"|"CONFLICT"|"UNKNOWN";
export type PriceSource="DROPSHIP_PRICE"|"SKU_PRICE"|"WHOLESALE_PRICE"|"WHOLESALE_STARTING_PRICE"|"SEARCH_DISPLAY_PRICE"|"UNKNOWN";
export type SourceNodeType="SKU_SPEC"|"SERVICE_INFO"|"MARKETING_TEXT"|"UNKNOWN";

export interface RawSourceOption{sourceVariantId:string;variantName:string;specValues:string[];price:number|null;stock:number|null;image?:string|null;minOrderQuantity:number|null;rawSpecText?:string;rawPriceText?:string|null;priceSource?:PriceSource|string;nodeType?:SourceNodeType}
export interface SourceSkuRecord{id:string;sourceProductId:string;skuId?:string;specName:string;specValues:string[];rawSpecText:string;rawPriceText:string|null;priceSource:PriceSource;priceStatus:PriceStatus;wholesalePrice:number|null;wholesaleMoq:number|null;dropshipPrice:number|null;dropshipMoq:number|null;inventory:number|null;image:string|null;status:"ACTIVE"|"UNKNOWN"|"SPEC_AMBIGUOUS";targetSalePriceMin:number|null;targetSalePriceMax:number|null;estimatedProfitMin:number|null;estimatedProfitMax:number|null;landedCost:number|null;shippingFee:number|null;shippingConfidence:string;promotionDiscount:number|null}
export interface SourceProductRecord{id:string;sourceOfferId:string;externalOfferId:string;normalizedName:string;productType:string;featureTags:string[];image:string|null;status:"ACTIVE"|"REVIEW_REQUIRED";confidence:number;originalOptions:string[];skus:SourceSkuRecord[]}
export interface SourceProductParseResult{products:SourceProductRecord[];filteredOptions:Array<{text:string;reason:string;nodeType:SourceNodeType}>;ambiguousOptions:Array<{text:string;reason:string;nodeType:SourceNodeType}>}

export type SourceParseInput={sourceOfferId:string;externalOfferId:string;supportsDropshipping:boolean|null;onePiecePrice:boolean|null;options:RawSourceOption[]}

const servicePattern=/密文代发|代发下单|1件价格|退货包运费|48小时发货|晚发必赔|极速退款|运费险|客服|包邮|先采后付/;
const marketingPattern=/官方验货|品质保障|下单返.*样费|拿样费|新人价|会员价|爆款|官方推荐|优惠券|券后价/;
const productSignal=/隧道|通道|地龙|猫窝|响纸|纸袋|抓板|逗猫/;
const noisyVariantPattern=/钢丝材质|品质保障|官方验货|下单返.*样费|品牌|产品类别|官方|店铺|承诺|支持|不支持|先采后付|包邮|返现|售后|运费险|客服|退款|退货|质保/;

const clean=(value:string)=>value.replace(/\s+/g," ").replace(/^[颜色规格款式：:]+/," ").trim();
const trimPriceStock=(value:string)=>value.replace(/[¥￥]\s*\d+(?:\.\d+)?/g,"").replace(/库存\d+\s*个?/g,"").replace(/\s+/g," ").trim();
const colors=["彩虹","彩色","红色","黄色","蓝色","绿色","橙色","紫色","粉色","灰色","米色","咖色","抹茶绿","鹅黄色","浅咖色","浅咖","白色","黑色","棕色","深灰","浅灰","米白","军绿","藏蓝"];
const sizes=["小号","大号","中号","加大","超大","短款","长款","加长","加长款","迷你","中大","X大","2号","3号","4号","5号","6号"];

function extractColorKeywords(value:string){return [...new Set(colors.filter(x=>new RegExp(x,"i").test(value)))];}
function extractSizeKeywords(value:string){return [...new Set(sizes.filter(x=>new RegExp(x,"i").test(value)))];}
function extractSpecs(value:string){return [...extractColorKeywords(value),...extractSizeKeywords(value)].filter(Boolean);}

const isProductNoise=(text:string)=>noisyVariantPattern.test(text);

function normalizeSpecName(raw:string,baseName:string){const cleaned=trimPriceStock(clean(raw)).replace(/^[\-|_:\/（(\[]+/g,"").trim();if(!cleaned||isProductNoise(cleaned))return"";const tokens=cleaned.split(/[-_（）()\[\]【】]/).map(x=>x.trim()).filter(Boolean);const candidate=tokens.length>1?tokens[tokens.length-1]:cleaned;const colorsFound=extractColorKeywords(candidate);const sizesFound=extractSizeKeywords(candidate);const known=[...colorsFound,...sizesFound].sort((a,b)=>b.length-a.length);const descriptors=known.length?candidate.replace(new RegExp(known.join("|"),"g"),"").replace(/[\s/·_-]+/g,"").trim():candidate;if(!descriptors&&colorsFound.length===1&&sizesFound.length===1)return `${sizesFound[0]} ${colorsFound[0]}`.trim();if(!descriptors&&colorsFound.length===1)return colorsFound[0];if(!descriptors&&colorsFound.length===0&&sizesFound.length===1)return sizesFound[0];const fallback=candidate.replace(new RegExp(baseName,"ig"),"").replace(/\([^)]*\)/g,"").replace(/\s+/g," ").trim();return fallback||candidate;}
function likelyAggregate(text:string){const hasSep=/[、，,；;\/]|\s+和\s+|\s+及\s+/.test(text);const signals=extractSpecs(text);return hasSep&&signals.length>=2;}

const classifyNode=(text:string):SourceNodeType=>{if(servicePattern.test(text))return"SERVICE_INFO";if(marketingPattern.test(text))return"MARKETING_TEXT";if(isProductNoise(text))return"UNKNOWN";if(productSignal.test(text))return"SKU_SPEC";return"UNKNOWN"}

function classify(text:string){if(/猫窝|窝隧/.test(text))return{key:"nest-tunnel",name:"猫窝一体猫隧道",type:"猫窝一体",tags:["猫窝一体"]};if(/T型|T形|三通|三岔|三口/.test(text))return{key:"three-way",name:/彩虹|彩色/.test(text)?"彩虹 T 型三通猫隧道":"T 型三通猫隧道",type:"三通道",tags:["三通道",...(/彩虹|彩色/.test(text)?["彩虹"]:[])]};if(/S型|S形|^S通道/i.test(text))return{key:"s-shaped",name:"S 型猫隧道",type:"S型",tags:["S型"]};if(/兔耳/.test(text))return{key:"rabbit-plush",name:"兔耳造型绒布猫隧道",type:"造型绒布",tags:["兔耳","绒布","造型"]};if(/抓板/.test(text))return{key:"scratcher",name:"抓板一体猫隧道",type:"抓板一体",tags:["抓板"]};if(/绒布/.test(text)&&/通道|隧道/.test(text))return{key:"plush-straight",name:"绒布直筒猫隧道",type:"绒布直筒",tags:["绒布","直筒"]};if(/毛毡/.test(text))return{key:"felt",name:"毛毡猫隧道",type:"毛毡",tags:["毛毡"]};if(/响纸|纸袋/.test(text))return{key:"crinkle",name:"响纸类猫玩具",type:"响纸",tags:["响纸"]};if(/直通|直筒|一字|隧道|通道|地龙/.test(text))return{key:"straight",name:"基础直筒猫隧道",type:"基础直筒",tags:["直筒"]};return null}

function ambiguity(text:string){return[/T型|T形|T字型|三通|三岔|三口/.test(text),/S型|S形|S通/i.test(text),/猫窝|窝隧/.test(text),/兔耳/.test(text),/响纸|纸袋/.test(text),/直通|直筒|长直通|一字/.test(text)].filter(Boolean).length>1}
function skuValues(text:string){const dimension=text.match(/\d+(?:\.\d+)?\s*(?:cm|厘米|米)/gi);return[...new Set([...colors.filter(x=>text.includes(x)),...sizes.filter(x=>text.includes(x)),...(dimension??[])])]} 
function safeKey(value:string){let hash=0;for(const char of value)hash=(hash*31+char.charCodeAt(0))>>>0;return hash.toString(36)}
function normalizedSource(value:string|undefined):PriceSource{return(["DROPSHIP_PRICE","SKU_PRICE","WHOLESALE_PRICE","WHOLESALE_STARTING_PRICE","SEARCH_DISPLAY_PRICE"] as const).find(x=>x===value)??"UNKNOWN"}
function priceEvidence(option:RawSourceOption){const parsed=option.price,rawText=option.rawPriceText??option.rawSpecText??option.variantName,rawMatch=/[¥￥]\s*(\d+(?:\.\d+)?)/.exec(rawText),rawPrice=rawMatch?Number(rawMatch[1]):null,source=normalizedSource(option.priceSource);if(parsed==null)return{status:"UNKNOWN" as PriceStatus,source,rawText:option.rawPriceText??rawMatch?.[0]??null};if(source==="SEARCH_DISPLAY_PRICE"||source==="WHOLESALE_STARTING_PRICE")return{status:"NEEDS_REVIEW" as PriceStatus,source,rawText:option.rawPriceText??rawMatch?.[0]??null};if(rawPrice!=null&&Math.abs(rawPrice-parsed)>Math.max(1,rawPrice*.2))return{status:"CONFLICT" as PriceStatus,source,rawText:option.rawPriceText??rawMatch?.[0]??null};if(source==="DROPSHIP_PRICE")return{status:"VERIFIED" as PriceStatus,source,rawText:option.rawPriceText??rawMatch?.[0]??null};if(source==="SKU_PRICE"||source==="WHOLESALE_PRICE")return{status:"HIGH_CONFIDENCE" as PriceStatus,source,rawText:option.rawPriceText??rawMatch?.[0]??null};return{status:"NEEDS_REVIEW" as PriceStatus,source,rawText:option.rawPriceText??rawMatch?.[0]??null}}
export const isTrustedPrice=(sku:SourceSkuRecord)=>sku.priceStatus==="VERIFIED"||sku.priceStatus==="HIGH_CONFIDENCE";

export function parseSourceProducts(input:SourceParseInput):SourceProductParseResult{
 const groups=new Map<string,{meta:NonNullable<ReturnType<typeof classify>>;options:RawSourceOption[]}>(),filteredOptions:SourceProductParseResult["filteredOptions"]=[] ,ambiguousOptions:SourceProductParseResult["ambiguousOptions"]=[];
 for(const raw of input.options){const text=clean(raw.variantName),nodeType=raw.nodeType??classifyNode(text);if(nodeType!=="SKU_SPEC"){filteredOptions.push({text:text||raw.variantName,reason:nodeType==="UNKNOWN"?"NO_PRODUCT_SIGNAL":nodeType,nodeType});continue}if(ambiguity(text)){ambiguousOptions.push({text,reason:"SPEC_AMBIGUOUS_MULTIPLE_PRODUCT_FORMS",nodeType});continue}const meta=classify(text)??{key:"original-sku",name:"原始 SourceSKU",type:"原始规格",tags:[]};const current=groups.get(meta.key);groups.set(meta.key,{meta,options:[...(current?.options??[]),raw]})}
 const products=[...groups.entries()].map(([key,group])=>{const productId=`product:${input.externalOfferId}:${key}`,baseName=group.meta.name,unique=new Map<string,RawSourceOption>();for(const option of group.options){const skuKey=clean(option.rawSpecText??option.variantName);if(!unique.has(skuKey))unique.set(skuKey,option)}
   const parsedSkus=[...unique.entries()].map(([_,option],index)=>{const values=skuValues(option.variantName),evidence=priceEvidence(option),trusted=evidence.status==="VERIFIED"||evidence.status==="HIGH_CONFIDENCE",dropshipEligible=input.supportsDropshipping===true&&input.onePiecePrice===true,wholesalePrice=trusted?option.price:null,dropshipPrice=trusted&&dropshipEligible?option.price:null;const rawText=option.rawSpecText??option.variantName;const normalizedName=normalizeSpecName(rawText,baseName);const inferredSignals=extractSpecs(rawText);const priceText=normalizedName||inferredSignals.join("/");const candidateSpec=normalizedName||priceText;return{id:`sku:${input.externalOfferId}:${key}:${safeKey(option.variantName||String(index))}`,sourceProductId:productId,specName:candidateSpec||"待核实",specValues:inferredSignals,rawSpecText:rawText,rawPriceText:evidence.rawText,priceSource:evidence.source,priceStatus:evidence.status,wholesalePrice,wholesaleMoq:option.minOrderQuantity,dropshipPrice,dropshipMoq:dropshipEligible?1:null,inventory:option.stock,image:option.image??null,status:evidence.status==="CONFLICT"?"SPEC_AMBIGUOUS":evidence.status==="UNKNOWN"?"UNKNOWN":"ACTIVE",targetSalePriceMin:null,targetSalePriceMax:null,estimatedProfitMin:null,estimatedProfitMax:null,landedCost:null,shippingFee:null,shippingConfidence:"UNKNOWN",promotionDiscount:null} satisfies SourceSkuRecord});
   const skus=parsedSkus.filter((sku,index,all)=>{const signalCount=extractSpecs(sku.rawSpecText).length;if(!likelyAggregate(sku.rawSpecText)||signalCount<=1){return true;}const matched=all.filter((item,inner)=>inner!==index&&item.specName&&sku.specName&&extractSpecs(item.specName).some(v=>extractSpecs(sku.specName).includes(v)));return !(matched.length>=2);});
   const trusted=skus.filter(isTrustedPrice),known=[input.supportsDropshipping!=null,input.onePiecePrice!=null,...skus.flatMap(s=>[s.inventory!=null,s.priceStatus!=="UNKNOWN",s.wholesaleMoq!=null])],confidence=Math.round(known.filter(Boolean).length/Math.max(1,known.length)*100);return{id:productId,sourceOfferId:input.sourceOfferId,externalOfferId:input.externalOfferId,normalizedName:group.meta.name,productType:group.meta.type,featureTags:group.meta.tags,image:skus.find(s=>s.image)?.image??null,status:trusted.length?"ACTIVE":"REVIEW_REQUIRED",confidence,originalOptions:group.options.map(x=>x.variantName),skus} satisfies SourceProductRecord});return{products,filteredOptions,ambiguousOptions}
}
