import type { RawSourceOption } from "./source-products";

export type SourceRole="MAIN_PRODUCT"|"ACCESSORY"|"BUNDLE"|"REPLACEMENT"|"IRRELEVANT"|"UNKNOWN";
export type SizeMatchStatus="EXACT"|"CLOSE"|"DIFFERENT"|"UNKNOWN";
export type SourceMatchStatus="MATCH"|"ALTERNATIVE"|"NOT_MATCH";
export type V3PriceStatus="UNVERIFIED"|"SKU_PARSED"|"VARIANT_MATCHED"|"COST_VERIFIED";
export interface CategorySchema{id:string;productFamily:string;modelKeys:string[];variantKeys:string[];dimensionKeys:string[]}
export interface NormalizedDimensions{schemaId:string;length_cm?:number;diameter_cm?:number;width_cm?:number;height_cm?:number;thickness_cm?:number;weight_g?:number}
export interface V3SourceSku{id:string;offerId:string;externalOfferId:string;sourceUrl:string;supplierName:string;rawName:string;rawProperties:Record<string,unknown>;image:string|null;price:number|null;stock:number|null;rawSize:string|null;rawColor:string|null;rawMaterial:string|null;productFamily:string;structure:string|null;color:string|null;material:string|null;feature:string[];packageInfo:Record<string,unknown>;quantity:number|null;role:SourceRole;normalizedDimensions:NormalizedDimensions;dimensionStatus:"KNOWN"|"PARTIAL"|"UNKNOWN";confidence:number;evidence:string[];priceStatus:V3PriceStatus;capturedAt:string|null}
export interface V3SourceMatch{sourceSkuId:string;status:SourceMatchStatus;sizeMatchStatus:SizeMatchStatus;confidence:number;evidence:string[]}
export interface V3Variant{id:string;modelId:string;name:string;attributes:Record<string,unknown>;dimensionStatus:"KNOWN"|"PARTIAL"|"UNKNOWN";priceStatus:V3PriceStatus;matches:V3SourceMatch[];strictComparableCount:number;alternativeCount:number}
export interface V3ProductModel{id:string;name:string;productFamily:string;structure:string|null;representativeImage:string|null;sourceSkuIds:string[];supplierCount:number;sizeCompleteness:number;variantIds:string[];matchCount:number;pendingCount:number;definition:string;evidence:string[]}
export interface SourcingV3Graph{schema:CategorySchema;sourceSkus:V3SourceSku[];unidentifiedSourceSkuIds:string[];models:V3ProductModel[];variants:V3Variant[];counts:{offers:number;sourceSkus:number;models:number;variants:number;comparableSources:number;accessories:number;unknownDimensions:number}}

export const categorySchemas:CategorySchema[]=[
 {id:"cat-tunnel-v1",productFamily:"猫隧道",modelKeys:["structure"],variantKeys:["color","dimensions","material","quantity","package"],dimensionKeys:["length_cm","diameter_cm","weight_g"]},
 {id:"cat-bed-v1",productFamily:"猫窝",modelKeys:["structure"],variantKeys:["color","dimensions","material"],dimensionKeys:["length_cm","width_cm","height_cm","weight_g"]},
 {id:"cat-scratcher-v1",productFamily:"猫抓板",modelKeys:["structure"],variantKeys:["color","dimensions","material"],dimensionKeys:["length_cm","width_cm","thickness_cm","weight_g"]},
 {id:"generic-v1",productFamily:"通用商品",modelKeys:["structure"],variantKeys:["color","dimensions","material","quantity","package"],dimensionKeys:["length_cm","width_cm","height_cm","weight_g"]},
];
const tunnelStructures:Array<[RegExp,string]>=[[/小两通|双通|两通/,"双通型"],[/三通|三岔|三口|T\s*字?型?/i,"三通型"],[/8\s*字?型?/,"8字型"],[/6\s*字?型?/,"6字型"],[/Y\s*字?型?/i,"Y型"],[/S\s*字?型?/i,"S型"],[/U\s*字?型?/i,"U型"],[/凸\s*字?型?/,"凸型"],[/1\s*字?型?|一\s*字?型?|直筒|直通/,"直筒型"],[/巨型/,"巨型"],[/猫窝|窝隧/,"猫窝一体型"]];
const colors=["彩虹","彩色","蓝黑","米白","米色","红色","黄色","蓝色","绿色","橙色","紫色","粉色","灰色","白色","黑色","棕色"];
const materials=["毛毡","长毛绒","短毛绒","涤纶","聚酯纤维","牛津布","帆布","钢丝","响纸"];
const clean=(v:string)=>v.replace(/[¥￥]\s*\d+(?:\.\d+)?/g,"").replace(/库存\s*\d+\s*个?/g,"").replace(/已售\s*\d+\s*个?/g,"").replace(/\s+/g," ").trim();
const attributeNoise=/(?:产品类别|产品类目|品牌|材质|产地|货号|适用对象|是否进口|箱装数量|主要下游平台|主要销售地区)/;
function isRealSkuOption(option:RawSourceOption){const raw=String(option.rawSpecText??option.variantName??"");if(attributeNoise.test(raw))return false;const text=clean(raw);return text.length>1&&!/^(?:猫隧道|聚酯纤维|其他)$/.test(text)}
const key=(v:string)=>{let h=0;for(const c of v)h=(h*31+c.charCodeAt(0))>>>0;return h.toString(36)};
function familyFor(query:string){if(/隧道|通道|地龙/.test(query))return"猫隧道";if(/猫窝|宠物窝/.test(query))return"猫窝";if(/抓板/.test(query))return"猫抓板";return clean(query)||"通用商品"}
function schemaFor(family:string){return categorySchemas.find(x=>x.productFamily===family)??{...categorySchemas.at(-1)!,productFamily:family}}
function dimensions(text:string,schema:CategorySchema):{value:NormalizedDimensions;status:"KNOWN"|"PARTIAL"|"UNKNOWN";raw:string|null}{
 const value:NormalizedDimensions={schemaId:schema.id},raw=text.match(/(?:\d+(?:\.\d+)?\s*(?:cm|厘米|米))(?:\s*[×xX*]\s*\d+(?:\.\d+)?\s*(?:cm|厘米|米))*/i)?.[0]??text.match(/(?:小号|中号|大号|加大号|超大号|M|L|XL)/i)?.[0]??null;
 const unit=(n:string,u:string)=>Number(n)*(u==="米"?100:1),multi=[...text.matchAll(/(\d+(?:\.\d+)?)\s*(cm|厘米|米)/gi)].map(m=>unit(m[1],m[2]));
 const diameter=text.match(/(?:直径|口径|管径|φ|Φ)\s*(\d+(?:\.\d+)?)\s*(cm|厘米|米)/i);if(diameter)value.diameter_cm=unit(diameter[1],diameter[2]);
 const weight=text.match(/(\d+(?:\.\d+)?)\s*(kg|千克|公斤|g|克)/i);if(weight)value.weight_g=Number(weight[1])*(/kg|千克|公斤/i.test(weight[2])?1000:1);
 if(multi.length){value.length_cm=multi[0];if(schema.dimensionKeys.includes("width_cm")&&multi[1]!=null)value.width_cm=multi[1];if(schema.dimensionKeys.includes("height_cm")&&multi[2]!=null)value.height_cm=multi[2];if(schema.dimensionKeys.includes("diameter_cm")&&value.diameter_cm==null&&multi[1]!=null)value.diameter_cm=multi[1]}
 const known=Object.keys(value).length-1;return{value,status:known>=Math.min(2,schema.dimensionKeys.length)?"KNOWN":known?"PARTIAL":"UNKNOWN",raw};
}
function normalize(raw:RawSourceOption,offer:Record<string,unknown>,family:string,schema:CategorySchema):V3SourceSku{
 const rawName=clean(raw.variantName||raw.rawSpecText||""),text=[rawName,raw.rawSpecText??""].join(" "),structure=tunnelStructures.find(([re])=>re.test(text))?.[1]??null,color=colors.find(x=>text.includes(x))??null,material=materials.find(x=>text.includes(x))??null,dim=dimensions(text,schema);
 const role:SourceRole=/垫子|地垫|配件|附件/.test(text)?"ACCESSORY":/替换|替换装/.test(text)?"REPLACEMENT":/套装|组合装/.test(text)?"BUNDLE":structure||/隧道|通道|地龙/.test(text)?"MAIN_PRODUCT":"UNKNOWN";
 const evidence=[structure&&`SKU 名称识别结构：${structure}`,color&&`SKU 名称识别颜色：${color}`,material&&`SKU 名称识别材质：${material}`,dim.raw&&`保留原始尺寸：${dim.raw}`,role!=="MAIN_PRODUCT"&&`SKU 角色：${role}`].filter((x):x is string=>Boolean(x));
 return{id:`v3sku:${offer.id}:${key(raw.sourceVariantId||rawName)}`,offerId:String(offer.id),externalOfferId:String(offer.external_id??offer.id),sourceUrl:String(offer.source_url),supplierName:String(offer.supplier_name??"供应商待核实"),rawName,rawProperties:{specValues:raw.specValues,rawSpecText:raw.rawSpecText,nodeType:raw.nodeType,priceSource:raw.priceSource},image:raw.image??null,price:raw.price,stock:raw.stock,rawSize:dim.raw,rawColor:raw.variantName,rawMaterial:material,productFamily:family,structure,color:color==="彩色"?"彩虹":color,material,feature:[],packageInfo:{},quantity:null,role,normalizedDimensions:dim.value,dimensionStatus:dim.status,confidence:Math.round((structure?40:0)+(role!=="UNKNOWN"?20:0)+(dim.status!=="UNKNOWN"?20:0)+(color?10:0)+(material?10:0)),evidence,priceStatus:raw.price==null?"UNVERIFIED":"SKU_PARSED",capturedAt:String(((offer.raw_data as Record<string,unknown>)?.detailEnrichment as Record<string,unknown>)?.capturedAt??"")||null};
}
const dimSignature=(s:V3SourceSku)=>Object.entries(s.normalizedDimensions).filter(([k])=>k!=="schemaId").sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}:${v}`).join("|");
function sizeMatch(a:V3SourceSku,b:V3SourceSku):SizeMatchStatus{const x=dimSignature(a),y=dimSignature(b);if(!x||!y)return"UNKNOWN";return x===y?"EXACT":"DIFFERENT"}
export function buildSourcingV3(rows:Record<string,unknown>[],query:string):SourcingV3Graph{
 const family=familyFor(query),schema=schemaFor(family),sourceSkus=rows.flatMap(offer=>{const detail=((offer.raw_data??{})as Record<string,unknown>).detailEnrichment as Record<string,unknown>|undefined,options=Array.isArray(detail?.rawOptions)?detail.rawOptions as RawSourceOption[]:Array.isArray(detail?.variants)?detail.variants as RawSourceOption[]:[];return options.filter(x=>(x.nodeType??"SKU_SPEC")==="SKU_SPEC"&&isRealSkuOption(x)).map(x=>normalize(x,offer,family,schema))});
 const main=sourceSkus.filter(x=>x.role==="MAIN_PRODUCT"&&x.structure),unidentifiedSourceSkuIds=sourceSkus.filter(x=>x.role==="UNKNOWN"||(x.role==="MAIN_PRODUCT"&&!x.structure)).map(x=>x.id),modelGroups=new Map<string,V3SourceSku[]>();for(const sku of main){const mk=sku.structure!;modelGroups.set(mk,[...(modelGroups.get(mk)??[]),sku])}
 const variants:V3Variant[]=[],models:V3ProductModel[]=[];
 for(const [structure,skus] of modelGroups){const modelId=`model:${key(`${family}:${structure}`)}`,variantGroups=new Map<string,V3SourceSku[]>();for(const sku of skus){const dims=dimSignature(sku),base=[sku.color??"颜色待确认",dims||`尺寸待确认:${sku.id}`,sku.material??"材质待确认"].join("|");variantGroups.set(base,[...(variantGroups.get(base)??[]),sku])}const ids:string[]=[];for(const [sig,group] of variantGroups){const sample=group[0],variantId=`variant:${key(`${modelId}:${sig}`)}`,strict=group.filter(x=>x.dimensionStatus!=="UNKNOWN"),alternatives=skus.filter(x=>!group.includes(x)&&sizeMatch(sample,x)!=="DIFFERENT");ids.push(variantId);variants.push({id:variantId,modelId,name:[sample.color, sample.rawSize, sample.material].filter(Boolean).join(" / ")||"规格待确认",attributes:{structure:sample.structure,color:sample.color,dimensions:sample.normalizedDimensions,material:sample.material},dimensionStatus:sample.dimensionStatus,priceStatus:strict.length?"VARIANT_MATCHED":"SKU_PARSED",strictComparableCount:strict.length,alternativeCount:alternatives.length,matches:[...group.map(x=>({sourceSkuId:x.id,status:(x.dimensionStatus==="UNKNOWN"?"ALTERNATIVE":"MATCH") as SourceMatchStatus,sizeMatchStatus:(x.dimensionStatus==="UNKNOWN"?"UNKNOWN":"EXACT") as SizeMatchStatus,confidence:x.confidence,evidence:x.evidence})),...alternatives.map(x=>({sourceSkuId:x.id,status:"ALTERNATIVE" as const,sizeMatchStatus:sizeMatch(sample,x),confidence:Math.min(sample.confidence,x.confidence),evidence:["结构相同，但关键规格不足以进入严格比价"]}))]})}const suppliers=new Set(skus.map(x=>x.supplierName));models.push({id:modelId,name:`${structure.startsWith("待确认:")?"结构待确认":structure}${family}`,productFamily:family,structure:structure.startsWith("待确认:")?null:structure,representativeImage:skus.find(x=>x.image)?.image??null,sourceSkuIds:skus.map(x=>x.id),supplierCount:suppliers.size,sizeCompleteness:Math.round(skus.filter(x=>x.dimensionStatus!=="UNKNOWN").length/Math.max(1,skus.length)*100),variantIds:ids,matchCount:variants.filter(x=>x.modelId===modelId).reduce((n,x)=>n+x.strictComparableCount,0),pendingCount:skus.filter(x=>x.dimensionStatus==="UNKNOWN").length,definition:`由标准化 SourceSKU 的 structure=${structure.startsWith("待确认:")?"UNKNOWN":structure} 归类；未使用 Offer 标题。`,evidence:[`${skus.length} 个 SourceSKU 提供款型证据`,`${suppliers.size} 家供应商`]})}
 return{schema,sourceSkus,unidentifiedSourceSkuIds,models:models.sort((a,b)=>b.sourceSkuIds.length-a.sourceSkuIds.length),variants,counts:{offers:rows.length,sourceSkus:sourceSkus.length,models:models.length,variants:variants.length,comparableSources:variants.reduce((n,x)=>n+(x.strictComparableCount>1?x.strictComparableCount:0),0),accessories:sourceSkus.filter(x=>x.role==="ACCESSORY"||x.role==="IRRELEVANT").length,unknownDimensions:sourceSkus.filter(x=>x.dimensionStatus==="UNKNOWN").length}};
}
