"use client";
import { useState } from "react";
import type { SkuDiagnosis } from "@/lib/ai/types";
interface Meta { runId: string; model: string; latencyMs: number; createdAt: string }
export function SkuDiagnosisPanel({ skuId }: { skuId: string }) {
  const [analysis, setAnalysis] = useState<SkuDiagnosis | null>(null); const [meta, setMeta] = useState<Meta | null>(null); const [status, setStatus] = useState<"idle" | "loading" | "success" | "error">("idle"); const [error, setError] = useState("");
  async function analyze() { setStatus("loading"); setError(""); try { const response = await fetch("/api/ai/sku-diagnosis", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ skuId }) }); const payload = await response.json() as { analysis?: SkuDiagnosis; meta?: Meta; error?: string }; if (!response.ok || !payload.analysis || !payload.meta) { setStatus("error"); setError(payload.error ?? "分析失败"); return; } setAnalysis(payload.analysis); setMeta(payload.meta); setStatus("success"); } catch { setStatus("error"); setError("网络请求失败，请检查服务后重试"); } }
  return <section className="ai-panel card"><div className="section-heading compact"><div><div className="eyebrow">AI SKU Diagnosis</div><h2>AI 经营诊断</h2><p className="muted">仅在点击时调用；结果是建议，不会自动修改商品或价格。</p></div><button className="btn" type="button" disabled={status === "loading"} onClick={() => void analyze()}>{status === "loading" ? "分析中…" : analysis ? "重新分析" : "开始 AI 分析"}</button></div>{status === "idle" && <div className="empty-state">AI 将结合最近 1/7/30 天数据，判断主要问题、证据和建议动作。</div>}{status === "loading" && <div className="ai-loading" role="status"><span className="spinner"/>正在生成结构化诊断，通常需要数秒…</div>}{status === "error" && <div className="status-box error"><strong>分析失败</strong><p>{error}</p><button className="secondary-btn" type="button" onClick={() => void analyze()}>重试</button></div>}{analysis && status === "success" && <div className="diagnosis"><div className="diagnosis-head"><span className={`health ${analysis.health}`}>{analysis.health}</span><span className="priority">{analysis.priority}</span><span className="muted">置信度 {Math.round(analysis.confidence * 100)}%</span></div><h3>{analysis.summary}</h3><div className="diagnosis-grid"><div><h4>主要问题</h4><p>{analysis.primary_issue}</p><h4>证据</h4><ul>{analysis.evidence.map((item) => <li key={item}>{item}</li>)}</ul></div><div><h4>建议动作</h4><ol>{analysis.recommended_actions.map((item) => <li key={item}>{item}</li>)}</ol>{analysis.should_observe && <div className="observe-note">样本或证据不足，建议继续观察。</div>}</div></div>{meta && <div className="run-meta">Run {meta.runId.slice(0, 8)} · {meta.model} · {meta.latencyMs}ms · {new Date(meta.createdAt).toLocaleString("zh-CN")}</div>}</div>}</section>;
}
