import { contentPackageSchema, customerServiceSchema, dailyReportSchema, skuDiagnosisSchema, storeAnalysisSchema, weeklyReportSchema, type AiResult, type ContentPackage, type CustomerServiceDraft, type DailyReport, type SkuDiagnosis, type StoreAnalysis, type WeeklyReport } from "./types";
import { SKU_DIAGNOSIS_JSON_SCHEMA } from "./prompts/sku-analysis";
import { STORE_ANALYSIS_JSON_SCHEMA } from "./prompts/store-analysis";
import { CONTENT_JSON_SCHEMA } from "./prompts/content-generator";
import { CUSTOMER_SERVICE_JSON_SCHEMA } from "./prompts/customer-service";
import { DAILY_REPORT_SCHEMA, WEEKLY_REPORT_SCHEMA } from "./prompts/reports";
interface ChatResponse { model?: string; choices?: Array<{ message?: { content?: string } }>; usage?: { prompt_tokens?: number; completion_tokens?: number }; error?: { message?: string } }
function config() { const apiKey = process.env.OPENAI_API_KEY; const model = process.env.OPENAI_MODEL; const baseUrl = (process.env.OPENAI_BASE_URL || "https://api.openai.com/v1").replace(/\/$/, ""); if (!apiKey) throw new Error("缺少 OPENAI_API_KEY"); if (!model) throw new Error("缺少 OPENAI_MODEL"); return { apiKey, model, baseUrl }; }
function responseFormat(baseUrl:string,name:string,schema:object){return baseUrl.includes("api.deepseek.com")?{type:"json_object"}:{type:"json_schema",json_schema:{name,strict:true,schema}}}
export async function generateSkuDiagnosis(prompt: string): Promise<AiResult<SkuDiagnosis>> {
  const { apiKey, model, baseUrl } = config(); const started = performance.now();
  const response = await fetch(`${baseUrl}/chat/completions`, { method: "POST", headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" }, body: JSON.stringify({ model, messages: [{ role: "system", content: "只输出符合所给 JSON Schema 的 JSON 结果。" }, { role: "user", content: prompt }], response_format: responseFormat(baseUrl,"sku_diagnosis",SKU_DIAGNOSIS_JSON_SCHEMA), max_tokens:4096 }), signal: AbortSignal.timeout(120_000) });
  const payload = await response.json() as ChatResponse; if (!response.ok) throw new Error(payload.error?.message || `AI API 请求失败 (${response.status})`);
  const content = payload.choices?.[0]?.message?.content; if (!content) throw new Error("AI API 未返回结构化内容");
  let json: unknown; try { json = JSON.parse(content); } catch { throw new Error("AI 返回的内容不是有效 JSON"); }
  const parsed = skuDiagnosisSchema.safeParse(json); if (!parsed.success) throw new Error(`AI 输出未通过 Schema 校验：${parsed.error.issues[0]?.message ?? "未知错误"}`);
  return { data: parsed.data, model: payload.model || model, latencyMs: Math.round(performance.now() - started), usage: { inputTokens: payload.usage?.prompt_tokens, outputTokens: payload.usage?.completion_tokens } };
}
export async function generateStoreAnalysis(prompt:string):Promise<AiResult<StoreAnalysis>>{
  const {apiKey,model,baseUrl}=config();const started=performance.now();const response=await fetch(`${baseUrl}/chat/completions`,{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model,messages:[{role:"system",content:"只输出符合 JSON Schema 的结果。"},{role:"user",content:prompt}],response_format:responseFormat(baseUrl,"store_analysis",STORE_ANALYSIS_JSON_SCHEMA),max_tokens:4096}),signal:AbortSignal.timeout(120_000)});const payload=await response.json() as ChatResponse;if(!response.ok)throw new Error(payload.error?.message||`AI API 请求失败 (${response.status})`);const content=payload.choices?.[0]?.message?.content;if(!content)throw new Error("AI API 未返回结构化内容");let json:unknown;try{json=JSON.parse(content)}catch{throw new Error("AI 返回的内容不是有效 JSON")}const parsed=storeAnalysisSchema.safeParse(json);if(!parsed.success)throw new Error(`AI 输出未通过 Schema 校验：${parsed.error.issues[0]?.message??"未知错误"}`);return{data:parsed.data,model:payload.model||model,latencyMs:Math.round(performance.now()-started),usage:{inputTokens:payload.usage?.prompt_tokens,outputTokens:payload.usage?.completion_tokens}};
}
export async function generateContentPackage(prompt:string):Promise<AiResult<ContentPackage>>{const{apiKey,model,baseUrl}=config();const started=performance.now();const response=await fetch(`${baseUrl}/chat/completions`,{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model,messages:[{role:"system",content:"只输出符合 JSON Schema 的中文商品内容草稿。"},{role:"user",content:prompt}],response_format:responseFormat(baseUrl,"content_package",CONTENT_JSON_SCHEMA),max_tokens:4096}),signal:AbortSignal.timeout(120_000)});const payload=await response.json()as ChatResponse;if(!response.ok)throw new Error(payload.error?.message||`AI API 请求失败 (${response.status})`);const content=payload.choices?.[0]?.message?.content;if(!content)throw new Error("AI API 未返回结构化内容");let json:unknown;try{json=JSON.parse(content)}catch{throw new Error("AI 返回的内容不是有效 JSON")}const parsed=contentPackageSchema.safeParse(json);if(!parsed.success)throw new Error(`AI 输出未通过 Schema 校验：${parsed.error.issues[0]?.message??"未知错误"}`);return{data:parsed.data,model:payload.model||model,latencyMs:Math.round(performance.now()-started),usage:{inputTokens:payload.usage?.prompt_tokens,outputTokens:payload.usage?.completion_tokens}}}
export async function generateCustomerServiceDraft(prompt:string):Promise<AiResult<CustomerServiceDraft>>{const{apiKey,model,baseUrl}=config();const started=performance.now();const response=await fetch(`${baseUrl}/chat/completions`,{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model,messages:[{role:"system",content:"只输出符合 JSON Schema 的客服回复草稿。"},{role:"user",content:prompt}],response_format:responseFormat(baseUrl,"customer_service_draft",CUSTOMER_SERVICE_JSON_SCHEMA),max_tokens:4096}),signal:AbortSignal.timeout(120_000)});const payload=await response.json()as ChatResponse;if(!response.ok)throw new Error(payload.error?.message||`AI API 请求失败 (${response.status})`);const content=payload.choices?.[0]?.message?.content;if(!content)throw new Error("AI API 未返回结构化内容");let json:unknown;try{json=JSON.parse(content)}catch{throw new Error("AI 返回的内容不是有效 JSON")}const parsed=customerServiceSchema.safeParse(json);if(!parsed.success)throw new Error(`AI 输出未通过 Schema 校验：${parsed.error.issues[0]?.message??"未知错误"}`);return{data:parsed.data,model:payload.model||model,latencyMs:Math.round(performance.now()-started),usage:{inputTokens:payload.usage?.prompt_tokens,outputTokens:payload.usage?.completion_tokens}}}
async function generateReport<T>(prompt:string,name:string,schema:object,validate:(value:unknown)=>{success:true;data:T}|{success:false;error:{issues:Array<{message:string}>}}):Promise<AiResult<T>>{const{apiKey,model,baseUrl}=config();const started=performance.now();const response=await fetch(`${baseUrl}/chat/completions`,{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model,messages:[{role:"system",content:"只输出符合 JSON Schema 的中文经营报告。"},{role:"user",content:prompt}],response_format:responseFormat(baseUrl,name,schema),max_tokens:4096}),signal:AbortSignal.timeout(120_000)});const payload=await response.json()as ChatResponse;if(!response.ok)throw new Error(payload.error?.message||`AI API 请求失败 (${response.status})`);const content=payload.choices?.[0]?.message?.content;if(!content)throw new Error("AI API 未返回结构化内容");let json:unknown;try{json=JSON.parse(content)}catch{throw new Error("AI 返回的内容不是有效 JSON")}const parsed=validate(json);if(!parsed.success)throw new Error(`AI 输出未通过 Schema 校验：${parsed.error.issues[0]?.message??"未知错误"}`);return{data:parsed.data,model:payload.model||model,latencyMs:Math.round(performance.now()-started),usage:{inputTokens:payload.usage?.prompt_tokens,outputTokens:payload.usage?.completion_tokens}}}
export function generateDailyReport(prompt:string){return generateReport<DailyReport>(prompt,"daily_report",DAILY_REPORT_SCHEMA,value=>dailyReportSchema.safeParse(value))}
export function generateWeeklyReport(prompt:string){return generateReport<WeeklyReport>(prompt,"weekly_report",WEEKLY_REPORT_SCHEMA,value=>weeklyReportSchema.safeParse(value))}

