import { z } from "zod";
export const skuDiagnosisSchema = z.object({ summary: z.string().min(1), health: z.enum(["good", "warning", "critical"]), primary_issue: z.string().min(1), evidence: z.array(z.string()), recommended_actions: z.array(z.string()), priority: z.enum(["P0", "P1", "P2", "P3"]), confidence: z.number().min(0).max(1), should_observe: z.boolean() });
export type SkuDiagnosis = z.infer<typeof skuDiagnosisSchema>;
export interface AiUsage { inputTokens?: number; outputTokens?: number }
export interface AiResult<T> { data: T; model: string; latencyMs: number; usage: AiUsage }
export interface SkuDiagnosisInput { sku: { id: string; code: string; name: string; status: string; cost: number; salePrice: number; isDemo: boolean }; windows: { days1: unknown; days7: unknown; days30: unknown }; previousActions: string[]; previousSuggestions: string[] }
export const storeAnalysisSchema = z.object({ summary: z.string().min(1), priorities: z.array(z.object({ sku_id: z.string(), sku_code: z.string(), sku_name: z.string(), issue: z.string(), action: z.string(), priority: z.enum(["P0","P1","P2","P3"]), should_observe: z.boolean() })).min(1).max(5), should_not_change: z.array(z.string()), increase_investment: z.array(z.string()), elimination_candidates: z.array(z.string()), refund_anomalies: z.array(z.string()), store_trends: z.array(z.string()), confidence: z.number().min(0).max(1) });
export type StoreAnalysis = z.infer<typeof storeAnalysisSchema>;
export const contentPackageSchema=z.object({titles:z.array(z.object({title:z.string(),main_keyword:z.string(),differentiation_word:z.string(),search_intent:z.string()})).length(5),short_title:z.string(),selling_points:z.array(z.string()).length(5),one_line_description:z.string(),detail_sections:z.array(z.object({section:z.enum(["用户痛点","解决问题","核心卖点","使用场景","尺寸","材质","安装方式","注意事项","包装与售后"]),content:z.string()})).length(9),faqs:z.array(z.object({question:z.string(),answer:z.string(),category:z.string()})).min(3).max(8),fact_gaps:z.array(z.string())});
export type ContentPackage=z.infer<typeof contentPackageSchema>;
export const customerServiceSchema=z.object({risk:z.enum(["low","medium","high"]),can_auto_draft:z.boolean(),reason:z.string(),reply:z.string(),facts_used:z.array(z.string()),uncertainties:z.array(z.string()),requires_human_review:z.boolean()});
export type CustomerServiceDraft=z.infer<typeof customerServiceSchema>;
const reportTotalsSchema=z.object({revenue:z.number(),orders:z.number().int(),refund_orders:z.number().int(),ad_spend:z.number()});
export const dailyReportSchema=z.object({report_date:z.string(),overview:z.string(),totals:reportTotalsSchema,best_skus:z.array(z.string()),anomaly_skus:z.array(z.string()),notable_changes:z.array(z.string()),top_tasks:z.array(z.string()).length(3),observe_only:z.array(z.string()),confidence:z.number().min(0).max(1)});export type DailyReport=z.infer<typeof dailyReportSchema>;
export const weeklyReportSchema=z.object({period:z.string(),summary:z.string(),sales_performance:z.string(),sku_ranking:z.array(z.object({rank:z.number().int(),sku_code:z.string(),sku_name:z.string(),revenue:z.number()})),fastest_rising:z.array(z.string()),fastest_declining:z.array(z.string()),refund_anomalies:z.array(z.string()),experiment_results:z.array(z.string()),potential_candidates:z.array(z.string()),elimination_candidates:z.array(z.string()),next_week_priorities:z.array(z.string()).length(3),confidence:z.number().min(0).max(1)});export type WeeklyReport=z.infer<typeof weeklyReportSchema>;
