import Link from "next/link";

const links=[
  ["dashboard","Dashboard"],["products/discover","货源发现"],["products/candidates","选品池"],["content","内容制作"],["suppliers","供应商"],["skus","SKU"],["analytics/daily","经营数据"],["ai-manager","AI 店长"],["tasks","任务"],["experiments","实验"],["reports/daily","报告"],["settings","设置"],
];
const lifecycleLabels:Record<string,string>={DISCOVERED:"已发现",SOURCING:"找货中",CANDIDATE:"候选",CONTENT_PREP:"内容制作",READY:"待上架",TESTING:"测试销售",GROWING:"增长",STABLE:"稳定",DECLINING:"衰退",CLEARANCE:"清仓",STOPPED:"停止经营"};
const sampleSkus=[{code:"CAT-001",name:"双面静电除毛刷",price:12.9,cost:3.99,stock:0,status:"TESTING"},{code:"CAT-002",name:"猫咪益智漏食球",price:19.9,cost:6.8,stock:0,status:"CANDIDATE"},{code:"CAT-003",name:"可替换羽毛逗猫棒",price:15.9,cost:4.5,stock:0,status:"GROWING"}];

function Header({eyebrow,title,description}:{eyebrow?:string;title:string;description:string}){return <header className="top"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1><p className="muted">{description}</p></div><span className="review-badge">公开只读</span></header>}
function Dashboard(){return <><Header title="Dashboard" description="当前店铺状态与需要关注的问题（脱敏示例）"/><div className="grid">{[["近30天销售额","¥5,805"],["活跃 SKU","3"],["候选商品","8"],["待人工审核","2"]].map(([label,value])=><div className="card" key={label}><span className="muted">{label}</span><div className="metric">{value}</div></div>)}</div><div className="section-heading"><div><h2>今日经营重点</h2><p className="muted">由确定性规则与 AI 诊断共同生成</p></div></div><div className="analysis-columns"><div className="card"><h3>商品结构</h3><p>测试期 SKU 偏少，应优先完成候选商品核价。</p></div><div className="card"><h3>利润目标</h3><p>部分商品实际毛利可能低于 45%，需要核验到手成本。</p></div><div className="card"><h3>人工决策</h3><p>正式上架、改价和采购仍等待店主批准。</p></div></div></>}
function Discover(){return <><Header eyebrow="Sourcing Agent" title="货源发现与粗筛" description="低频采集、规则粗筛、同质聚类、AI 细筛、人工决定上新"/><div className="notice">只读镜像不会连接浏览器扩展、请求 1688 或调用 DeepSeek。</div><section className="card"><h2>品类选品任务</h2><div className="form-grid"><label>任务名称<div className="input">猫咪去毛清洁用品</div></label><label>搜索关键词<div className="input">宠物去毛器、沙发除猫毛、猫毛清理器</div></label></div><div className="sourcing-stats">{[["原始 listing","—"],["跨词去重","—"],["异常/硬淘汰","—"],["商品方向","—"],["可供 AI 复核","—"]].map(([a,b])=><div key={a}><b>{b}</b><span>{a}</span></div>)}</div></section><div className="empty-state">搜索、价格分析和一件代发核验列为后续优化项目。</div></>}
function Candidates(){return <><Header title="候选商品" description="规则过滤和 AI 复核后，等待人工决定的商品"/><section className="card table-wrap"><table className="table"><thead><tr><th>商品</th><th>品类</th><th>评分</th><th>阶段</th><th>结论</th></tr></thead><tbody>{sampleSkus.slice(1).map((sku,index)=><tr key={sku.code}><td>{sku.name}</td><td>猫咪玩具</td><td>{82-index*6}</td><td><span className="badge">人工待审</span></td><td>建议进入小规模测试</td></tr>)}</tbody></table></section></>}
function Content(){return <><Header eyebrow="Listing Production" title="上架内容制作" description="将货源资料转化为经过授权、合规检查和人工批准的淘宝上架资料包"/><div className="notice">AI 只生成内容草稿，不会自动发布商品或虚构未经核验的商品事实。</div><section className="card"><h2>双面静电除毛刷 · 上架资料包</h2><div className="review-policy-grid"><div><span>标题与卖点</span><strong>草稿已生成</strong></div><div><span>详情页</span><strong>9 屏草稿</strong></div><div><span>图片授权</span><strong>待核验</strong></div><div><span>合规检查</span><strong>待检查</strong></div></div><div className="package-status"><span>SKU 映射：待补充</span><span>定价方案：待核价</span><span>人工审核：待处理</span></div></section></>}
function Suppliers(){return <><Header title="供应商" description="供应商表现、合作风险和备选关系"/><section className="card table-wrap"><table className="table"><thead><tr><th>供应商</th><th>平台</th><th>定位</th><th>可靠性</th><th>状态</th></tr></thead><tbody><tr><td>供应商 A（脱敏）</td><td>1688</td><td>宠物清洁用品</td><td>回头率、发货与售后待核验</td><td><span className="badge">候选</span></td></tr><tr><td>供应商 B（脱敏）</td><td>1688</td><td>猫咪玩具</td><td>支持一件代发</td><td><span className="badge">观察</span></td></tr></tbody></table></section></>}
function Skus(){return <><Header title="SKU" description="从发现到停止经营的完整商品生命周期"/><section className="card table-wrap"><table className="table"><thead><tr><th>SKU</th><th>售价</th><th>到手成本</th><th>库存</th><th>生命周期</th></tr></thead><tbody>{sampleSkus.map(sku=><tr key={sku.code}><td>{sku.code} · {sku.name}</td><td>¥{sku.price}</td><td>¥{sku.cost}</td><td>{sku.stock}</td><td><span className={`lifecycle ${sku.status.toLowerCase()}`}>{lifecycleLabels[sku.status]}</span></td></tr>)}</tbody></table></section><section className="card lifecycle-panel"><div className="eyebrow">Product Lifecycle</div><h2>状态路径</h2><div className="review-lifecycle">{Object.entries(lifecycleLabels).map(([key,label],index)=><div key={key}><b>{String(index+1).padStart(2,"0")}</b><span>{label}</span></div>)}</div></section></>}
function Analytics(){return <><Header title="经营数据" description="最近 7 天全店汇总 · 脱敏示例"/><div className="metric-grid">{[["曝光","12,480"],["点击率","3.2%"],["访客转化率","2.8%"],["退款率","6.1%"]].map(([label,value])=><div className="card" key={label}><span className="muted">{label}</span><div className="metric">{value}</div></div>)}</div><div className="card"><h2>趋势与 SKU 对比</h2><div className="empty-state">公开模式不展示真实订单、收入和用户数据。</div></div></>}
function Manager(){return <><Header eyebrow="Store Manager" title="经营决策中枢" description="观察店铺、诊断问题、规划行动、创建任务并等待复盘"/><section className="card manager-summary"><div className="eyebrow">最新判断</div><h2>起店期应优先验证商品—供应商—利润闭环</h2><ul><li>活跃测试 SKU 仍低于软目标</li><li>复杂促销价格不能作为可持续采购成本</li><li>关键外部动作继续由人工审核</li></ul></section><div className="proposal-list"><article className="card proposal-card"><div className="proposal-head"><div><span className="priority">P1</span><span className="permission approval">需人工批准</span><h2>完成候选 SKU 到手成本核验</h2></div><span className="proposal-status">待决策</span></div><p><b>判断：</b>常规价、优惠价、运费和一件代发价尚未完全拆分。</p><p><b>建议：</b>生成采购核价单，人工确认后再进入测试销售。</p></article></div></>}
function Tasks(){return <><Header title="任务" description="AI 自动准备与人工审核事项"/><div className="task-board"><div className="card"><span className="priority">P1</span><h3>核验候选商品可持续到手成本</h3><p className="muted">来源：AI 店长 · 待处理</p></div><div className="card"><span className="priority">P2</span><h3>建立 SKU 测试期健康度基线</h3><p className="muted">来源：规则引擎 · 待处理</p></div></div></>}
function Experiments(){return <><Header title="实验" description="主图、标题、价格等单变量测试"/><div className="card"><h2>暂无公开实验结果</h2><p className="muted">实验需要真实销售数据，公开审阅模式只展示流程结构。</p><div className="snapshot-grid"><div className="snapshot"><h4>Before 7 天</h4><span>CTR —</span><span>CVR —</span><span>毛利 —</span></div><div className="snapshot"><h4>After 7 天</h4><span>CTR —</span><span>CVR —</span><span>毛利 —</span></div></div></div></>}
function Reports(){return <><Header title="报告" description="AI 店长日报、周报与经营复盘"/><section className="card report-cover"><div className="eyebrow">AI 店长周报 · 公开示例</div><h1>当前重点是完成核心经营框架，而不是继续扩大采集范围。</h1><p>本周完成设置分层、SKU 生命周期和公开只读审阅；下一步建立 SKU Health。</p></section></>}
function Settings(){return <><Header eyebrow="Strategy & Production" title="设置" description="定义 AI 店长的目标函数与权限边界"/><section className="card"><div className="settings-tabs"><button className="active">经营策略</button><button>采购策略</button><button>AI 权限</button></div><div className="review-policy-grid">{[["店铺名称","AI 猫咪居家生活用品店"],["店铺阶段","起店期"],["主营类目","猫咪玩具与居家生活用品"],["核心客群","养猫家庭"],["目标毛利率","45%"],["目标 SKU","15～25（软目标）"],["库存周期","≤ 30 天"],["价格策略","利润优先"]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="notice">公开模式不可修改设置；正式后台继续使用 Supabase 登录保护。</div></section></>}

export default async function ReviewMirror({params}:{params:Promise<{slug?:string[]}>}){const{slug=[]}=await params,path=slug.join("/")||"dashboard";let content=<Dashboard/>;if(path==="products/discover")content=<Discover/>;else if(path==="products/candidates")content=<Candidates/>;else if(path==="content")content=<Content/>;else if(path==="suppliers")content=<Suppliers/>;else if(path==="skus")content=<Skus/>;else if(path==="analytics/daily")content=<Analytics/>;else if(path==="ai-manager")content=<Manager/>;else if(path==="tasks")content=<Tasks/>;else if(path==="experiments")content=<Experiments/>;else if(path==="reports/daily")content=<Reports/>;else if(path==="settings")content=<Settings/>;return <div className="shell"><aside className="side"><div className="brand">AI 店长</div><div className="review-badge">公开只读镜像</div><nav className="nav review-nav">{links.map(([href,label])=><Link className={path===href?"active":""} href={`/review/${href}`} key={href}>{label}</Link>)}</nav><Link href="/login" className="logout-btn button-link">登录正式后台</Link></aside><main className="main">{content}</main></div>}
