"use client";
import { useRef, useState } from "react";
import { parseDailyMetricsCsv, type CsvParseResult } from "@/lib/csv/daily-metrics";
type Status = "idle" | "reading" | "ready" | "importing" | "success" | "error";
const emptyResult: CsvParseResult = { rows: [], issues: [], headers: [], totalRows: 0 };
export function CsvImporter() {
  const inputRef = useRef<HTMLInputElement>(null); const [fileName, setFileName] = useState(""); const [result, setResult] = useState(emptyResult); const [status, setStatus] = useState<Status>("idle"); const [message, setMessage] = useState("");
  async function selectFile(file?: File) { if (!file) return; setMessage(""); setFileName(file.name); if (!file.name.toLowerCase().endsWith(".csv")) { setStatus("error"); setResult(emptyResult); setMessage("请选择 .csv 文件"); return; } if (file.size > 2 * 1024 * 1024) { setStatus("error"); setResult(emptyResult); setMessage("文件不能超过 2MB"); return; } setStatus("reading"); try { const parsed = parseDailyMetricsCsv(await file.text()); setResult(parsed); setStatus(parsed.issues.length ? "error" : "ready"); setMessage(parsed.issues.length ? `发现 ${parsed.issues.length} 个问题，请修正后重新选择文件。` : `校验通过，共 ${parsed.rows.length} 行，确认后才会写入数据库。`); } catch { setStatus("error"); setMessage("无法读取文件，请确认文件编码为 UTF-8。"); } }
  async function confirmImport() { if (status !== "ready" || !result.rows.length) return; setStatus("importing"); setMessage("正在写入数据库…"); try { const response = await fetch("/api/analytics/import", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ rows: result.rows }) }); const payload = await response.json() as { error?: string; imported?: number }; if (!response.ok) { setStatus("error"); setMessage(payload.error ?? "导入失败，请重试"); return; } setStatus("success"); setMessage(`成功导入 ${payload.imported ?? result.rows.length} 行经营数据。`); } catch { setStatus("error"); setMessage("网络请求失败，请检查开发服务器后重试。"); } }
  function reset() { setStatus("idle"); setMessage(""); setFileName(""); setResult(emptyResult); if (inputRef.current) inputRef.current.value = ""; }
  return <div className="import-stack"><section className="card upload-card"><h2>选择 CSV 文件</h2><p className="muted">仅在本地完成解析和预览，不会自动写入数据库。</p><input ref={inputRef} className="sr-only" id="csv-file" type="file" accept=".csv,text/csv" onChange={(event) => void selectFile(event.target.files?.[0])}/><label className="drop-zone" htmlFor="csv-file"><strong>{status === "reading" ? "正在读取…" : fileName || "点击选择 CSV 文件"}</strong><span>UTF-8 · 最大 2MB · 最多 5,000 行</span></label><a className="text-link" href="/examples/daily_metrics_template.csv" download>下载 CSV 示例模板</a></section>{message && <div className={`status-box ${status}`} role="status">{message}</div>}{result.issues.length > 0 && <section className="card"><h2>校验错误</h2><div className="table-wrap"><table className="table"><thead><tr><th>行号</th><th>字段</th><th>原因</th></tr></thead><tbody>{result.issues.slice(0, 100).map((issue, index) => <tr key={`${issue.row}-${issue.field}-${index}`}><td>第 {issue.row} 行</td><td><code>{issue.field}</code></td><td className="error-text">{issue.message}</td></tr>)}</tbody></table></div></section>}{result.rows.length > 0 && <section className="card"><div className="section-heading compact"><div><h2>数据预览</h2><p className="muted">显示前 20 行，共 {result.rows.length} 行有效数据</p></div></div><div className="table-wrap"><table className="table preview-table"><thead><tr>{["行", "日期", "SKU", "曝光", "点击", "访客", "加购", "订单", "销售额", "退款单", "广告费"].map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{result.rows.slice(0, 20).map((row, index) => <tr key={`${row.date}-${row.sku_code}`}><td>{index + 2}</td><td>{row.date}</td><td>{row.sku_code}</td><td>{row.impressions}</td><td>{row.clicks}</td><td>{row.visitors}</td><td>{row.add_to_cart}</td><td>{row.orders}</td><td>¥{row.revenue}</td><td>{row.refund_orders}</td><td>¥{row.ad_spend}</td></tr>)}</tbody></table></div></section>}{(status === "ready" || status === "importing" || status === "success" || (status === "error" && result.rows.length > 0)) && <div className="action-bar"><button className="secondary-btn" type="button" onClick={reset}>重新选择</button><button className="btn" type="button" disabled={status !== "ready"} onClick={() => void confirmImport()}>{status === "importing" ? "正在导入…" : status === "success" ? "导入完成" : "确认导入数据库"}</button></div>}</div>;
}
