"use server";
import {revalidatePath} from "next/cache";
import {createClient} from "@/lib/supabase/server";
import {requireUser} from "@/lib/data/auth";

const lifecycleStatuses=["DISCOVERED","SOURCING","CANDIDATE","READY","TESTING","GROWING","STABLE","DECLINING","CLEARANCE","STOPPED"] as const;
export async function saveSku(formData:FormData){const user=await requireUser();const supabase=await createClient();const id=String(formData.get("id")??"");const lifecycle=String(formData.get("lifecycle_status")??"TESTING");if(!lifecycleStatuses.includes(lifecycle as typeof lifecycleStatuses[number]))throw new Error("SKU 生命周期状态无效");const payload={user_id:user.id,sku_code:String(formData.get("code")??"").trim(),name:String(formData.get("name")??"").trim(),category:String(formData.get("category")??"").trim(),sale_price:Number(formData.get("price")??0),cost:Number(formData.get("cost")??0),stock:Number(formData.get("stock")??0),status:"testing" as const,lifecycle_status:lifecycle,is_demo:false};if(!payload.sku_code||!payload.name||!payload.category)throw new Error("SKU 编码、名称和品类不能为空");const{error}=await(id?supabase.from("skus").update(payload).eq("id",id):supabase.from("skus").insert(payload));if(error)throw new Error(error.message);revalidatePath("/skus")}
export async function transitionSkuLifecycle(formData:FormData){const user=await requireUser();const supabase=await createClient();const skuId=String(formData.get("sku_id")??""),toStatus=String(formData.get("to_status")??""),reason=String(formData.get("reason")??"").trim();if(!lifecycleStatuses.includes(toStatus as typeof lifecycleStatuses[number])||reason.length<3)throw new Error("请选择目标状态并填写变化原因");const{data:sku,error:readError}=await supabase.from("skus").select("lifecycle_status").eq("id",skuId).single();if(readError||!sku)throw new Error(readError?.message??"SKU 不存在");if(sku.lifecycle_status===toStatus)throw new Error("目标状态与当前状态相同");const approvalRequired=["READY","CLEARANCE","STOPPED"].includes(toStatus);const{error:eventError}=await supabase.from("sku_lifecycle_events").insert({user_id:user.id,sku_id:skuId,from_status:sku.lifecycle_status,to_status:toStatus,trigger_source:"manual",trigger_reason:reason,approval_required:approvalRequired,approval_status:approvalRequired?"approved":"not_required",execution_result:"人工已确认状态变更"});if(eventError)throw new Error(eventError.message);const{error:updateError}=await supabase.from("skus").update({lifecycle_status:toStatus,updated_at:new Date().toISOString()}).eq("id",skuId);if(updateError)throw new Error(updateError.message);revalidatePath(`/skus/${skuId}`);revalidatePath("/skus")}
export async function deleteSku(formData:FormData){await requireUser();const supabase=await createClient();const{error}=await supabase.from("skus").delete().eq("id",String(formData.get("id")));if(error)throw new Error(error.message);revalidatePath("/skus")}
