import { z } from "zod";
import { createClient } from "@/lib/supabase/server";

const nullableMoney=z.number().nonnegative().nullable(),nullableMoq=z.number().int().positive().nullable();
const schema=z.object({runId:z.string().uuid(),sourceOfferId:z.string().uuid(),sourceProductId:z.string(),sourceSkuId:z.string(),dropshipPrice:nullableMoney,dropshipMoq:nullableMoq,wholesalePrice:nullableMoney,wholesaleMoq:nullableMoq,shippingFee:nullableMoney,supportsPrivacyDropshipping:z.boolean().nullable(),evidenceNote:z.string().max(500).default("")});
export async function POST(request:Request){
 const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return Response.json({error:"人工核实参数无效"},{status:400});
 const db=await createClient(),{data:auth}=await db.auth.getUser();if(!auth.user)return Response.json({error:"请先登录"},{status:401});
 const [{data:row,error},{data:run}]=await Promise.all([db.from("source_products").select("id,raw_data").eq("id",parsed.data.sourceOfferId).eq("sourcing_run_id",parsed.data.runId).eq("user_id",auth.user.id).single(),db.from("sourcing_runs").select("id,criteria").eq("id",parsed.data.runId).eq("user_id",auth.user.id).single()]);if(error||!row||!run)return Response.json({error:"当前 Run 中未找到该 1688 Offer"},{status:404});
 const raw=(row.raw_data??{})as Record<string,unknown>,detail=(raw.detailEnrichment??{})as Record<string,unknown>,products=Array.isArray(detail.sourceProducts)?detail.sourceProducts as Array<Record<string,unknown>>:[],productIndex=products.findIndex(product=>product.id===parsed.data.sourceProductId);if(productIndex<0)return Response.json({error:"SourceProduct 不存在"},{status:404});
 const skus=Array.isArray(products[productIndex].skus)?products[productIndex].skus as Array<Record<string,unknown>>:[],skuIndex=skus.findIndex(sku=>sku.id===parsed.data.sourceSkuId);if(skuIndex<0)return Response.json({error:"SourceSku 不存在"},{status:404});
 const verifiedAt=new Date().toISOString(),verification={...parsed.data,verificationSource:"MANUAL_1688_PAGE",verifiedAt,verifiedBy:auth.user.id},manual=Array.isArray(detail.manualVerifications)?detail.manualVerifications as Array<Record<string,unknown>>:[],nextManual=[...manual.filter(entry=>!(entry.sourceProductId===parsed.data.sourceProductId&&entry.sourceSkuId===parsed.data.sourceSkuId)),verification];
 skus[skuIndex]={...skus[skuIndex],dropshipPrice:parsed.data.dropshipPrice,dropshipMoq:parsed.data.dropshipMoq,wholesalePrice:parsed.data.wholesalePrice,wholesaleMoq:parsed.data.wholesaleMoq,shippingFee:parsed.data.shippingFee,priceStatus:"VERIFIED",verificationSource:"MANUAL_1688_PAGE",verifiedAt,verifiedBy:auth.user.id,evidenceNote:parsed.data.evidenceNote};products[productIndex]={...products[productIndex],skus};
 const capabilities={...((detail.capabilities??{})as Record<string,unknown>),encryptedDropshipping:parsed.data.supportsPrivacyDropshipping},nextRaw={...raw,detailEnrichment:{...detail,capabilities,sourceProducts:products,manualVerifications:nextManual}};
 const {error:updateError}=await db.from("source_products").update({raw_data:nextRaw}).eq("id",row.id);if(updateError)return Response.json({error:updateError.message},{status:500});
 const criteria=(run.criteria??{})as Record<string,unknown>,pipeline=(criteria.pipeline??{})as Record<string,unknown>,stage2Version=Number(pipeline.stage2Version??0)+1,review=criteria.directionReview as Record<string,unknown>|undefined,history=Array.isArray(criteria.directionReviewHistory)?criteria.directionReviewHistory:[],stale=review?{...review,status:"STALE",invalidatedAt:verifiedAt,invalidatedReason:"MANUAL_1688_VERIFICATION",invalidatedByStage2Version:stage2Version}:undefined,nextCriteria={...criteria,pipeline:{...pipeline,stage2Status:"COMPLETED",stage2Version,stage2CompletedAt:verifiedAt,stage3Status:review?"STALE":"NOT_RUN"},directionReview:undefined,directionReviewHistory:stale?[...history,stale].slice(-10):history};
 const {error:runError}=await db.from("sourcing_runs").update({criteria:nextCriteria}).eq("id",run.id);if(runError)return Response.json({error:runError.message},{status:500});return Response.json({ok:true,verification,stage2Version,stage3Status:review?"STALE":"NOT_RUN"});
}
